// Code generated by ent, DO NOT EDIT.

package logcursor

import (
	"frappe-monitor/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLTE(FieldID, id))
}

// LogPath applies equality check predicate on the "log_path" field. It's identical to LogPathEQ.
func LogPath(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldLogPath, v))
}

// ByteOffset applies equality check predicate on the "byte_offset" field. It's identical to ByteOffsetEQ.
func ByteOffset(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldByteOffset, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldLastSeenAt, v))
}

// LogPathEQ applies the EQ predicate on the "log_path" field.
func LogPathEQ(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldLogPath, v))
}

// LogPathNEQ applies the NEQ predicate on the "log_path" field.
func LogPathNEQ(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNEQ(FieldLogPath, v))
}

// LogPathIn applies the In predicate on the "log_path" field.
func LogPathIn(vs ...string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldIn(FieldLogPath, vs...))
}

// LogPathNotIn applies the NotIn predicate on the "log_path" field.
func LogPathNotIn(vs ...string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNotIn(FieldLogPath, vs...))
}

// LogPathGT applies the GT predicate on the "log_path" field.
func LogPathGT(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGT(FieldLogPath, v))
}

// LogPathGTE applies the GTE predicate on the "log_path" field.
func LogPathGTE(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGTE(FieldLogPath, v))
}

// LogPathLT applies the LT predicate on the "log_path" field.
func LogPathLT(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLT(FieldLogPath, v))
}

// LogPathLTE applies the LTE predicate on the "log_path" field.
func LogPathLTE(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLTE(FieldLogPath, v))
}

// LogPathContains applies the Contains predicate on the "log_path" field.
func LogPathContains(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldContains(FieldLogPath, v))
}

// LogPathHasPrefix applies the HasPrefix predicate on the "log_path" field.
func LogPathHasPrefix(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldHasPrefix(FieldLogPath, v))
}

// LogPathHasSuffix applies the HasSuffix predicate on the "log_path" field.
func LogPathHasSuffix(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldHasSuffix(FieldLogPath, v))
}

// LogPathEqualFold applies the EqualFold predicate on the "log_path" field.
func LogPathEqualFold(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEqualFold(FieldLogPath, v))
}

// LogPathContainsFold applies the ContainsFold predicate on the "log_path" field.
func LogPathContainsFold(v string) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldContainsFold(FieldLogPath, v))
}

// ByteOffsetEQ applies the EQ predicate on the "byte_offset" field.
func ByteOffsetEQ(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldByteOffset, v))
}

// ByteOffsetNEQ applies the NEQ predicate on the "byte_offset" field.
func ByteOffsetNEQ(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNEQ(FieldByteOffset, v))
}

// ByteOffsetIn applies the In predicate on the "byte_offset" field.
func ByteOffsetIn(vs ...int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldIn(FieldByteOffset, vs...))
}

// ByteOffsetNotIn applies the NotIn predicate on the "byte_offset" field.
func ByteOffsetNotIn(vs ...int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNotIn(FieldByteOffset, vs...))
}

// ByteOffsetGT applies the GT predicate on the "byte_offset" field.
func ByteOffsetGT(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGT(FieldByteOffset, v))
}

// ByteOffsetGTE applies the GTE predicate on the "byte_offset" field.
func ByteOffsetGTE(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGTE(FieldByteOffset, v))
}

// ByteOffsetLT applies the LT predicate on the "byte_offset" field.
func ByteOffsetLT(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLT(FieldByteOffset, v))
}

// ByteOffsetLTE applies the LTE predicate on the "byte_offset" field.
func ByteOffsetLTE(v int64) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLTE(FieldByteOffset, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.LogCursor {
	return predicate.LogCursor(sql.FieldLTE(FieldLastSeenAt, v))
}

// HasServer applies the HasEdge predicate on the "server" edge.
func HasServer() predicate.LogCursor {
	return predicate.LogCursor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerWith applies the HasEdge predicate on the "server" edge with a given conditions (other predicates).
func HasServerWith(preds ...predicate.Server) predicate.LogCursor {
	return predicate.LogCursor(func(s *sql.Selector) {
		step := newServerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LogCursor) predicate.LogCursor {
	return predicate.LogCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LogCursor) predicate.LogCursor {
	return predicate.LogCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LogCursor) predicate.LogCursor {
	return predicate.LogCursor(sql.NotPredicates(p))
}
