// Code generated by ent, DO NOT EDIT.

package controlaction

import (
	"frappe-monitor/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldID, id))
}

// ServerID applies equality check predicate on the "server_id" field. It's identical to ServerIDEQ.
func ServerID(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldServerID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldAction, v))
}

// BenchPath applies equality check predicate on the "bench_path" field. It's identical to BenchPathEQ.
func BenchPath(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldBenchPath, v))
}

// Site applies equality check predicate on the "site" field. It's identical to SiteEQ.
func Site(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldSite, v))
}

// Command applies equality check predicate on the "command" field. It's identical to CommandEQ.
func Command(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldCommand, v))
}

// RequestedBy applies equality check predicate on the "requested_by" field. It's identical to RequestedByEQ.
func RequestedBy(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldRequestedBy, v))
}

// ExitOk applies equality check predicate on the "exit_ok" field. It's identical to ExitOkEQ.
func ExitOk(v bool) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldExitOk, v))
}

// Output applies equality check predicate on the "output" field. It's identical to OutputEQ.
func Output(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldOutput, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldError, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldDurationMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldCreatedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldFinishedAt, v))
}

// ServerIDEQ applies the EQ predicate on the "server_id" field.
func ServerIDEQ(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldServerID, v))
}

// ServerIDNEQ applies the NEQ predicate on the "server_id" field.
func ServerIDNEQ(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldServerID, v))
}

// ServerIDIn applies the In predicate on the "server_id" field.
func ServerIDIn(vs ...int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldServerID, vs...))
}

// ServerIDNotIn applies the NotIn predicate on the "server_id" field.
func ServerIDNotIn(vs ...int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldServerID, vs...))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldAction, v))
}

// BenchPathEQ applies the EQ predicate on the "bench_path" field.
func BenchPathEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldBenchPath, v))
}

// BenchPathNEQ applies the NEQ predicate on the "bench_path" field.
func BenchPathNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldBenchPath, v))
}

// BenchPathIn applies the In predicate on the "bench_path" field.
func BenchPathIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldBenchPath, vs...))
}

// BenchPathNotIn applies the NotIn predicate on the "bench_path" field.
func BenchPathNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldBenchPath, vs...))
}

// BenchPathGT applies the GT predicate on the "bench_path" field.
func BenchPathGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldBenchPath, v))
}

// BenchPathGTE applies the GTE predicate on the "bench_path" field.
func BenchPathGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldBenchPath, v))
}

// BenchPathLT applies the LT predicate on the "bench_path" field.
func BenchPathLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldBenchPath, v))
}

// BenchPathLTE applies the LTE predicate on the "bench_path" field.
func BenchPathLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldBenchPath, v))
}

// BenchPathContains applies the Contains predicate on the "bench_path" field.
func BenchPathContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldBenchPath, v))
}

// BenchPathHasPrefix applies the HasPrefix predicate on the "bench_path" field.
func BenchPathHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldBenchPath, v))
}

// BenchPathHasSuffix applies the HasSuffix predicate on the "bench_path" field.
func BenchPathHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldBenchPath, v))
}

// BenchPathIsNil applies the IsNil predicate on the "bench_path" field.
func BenchPathIsNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIsNull(FieldBenchPath))
}

// BenchPathNotNil applies the NotNil predicate on the "bench_path" field.
func BenchPathNotNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotNull(FieldBenchPath))
}

// BenchPathEqualFold applies the EqualFold predicate on the "bench_path" field.
func BenchPathEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldBenchPath, v))
}

// BenchPathContainsFold applies the ContainsFold predicate on the "bench_path" field.
func BenchPathContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldBenchPath, v))
}

// SiteEQ applies the EQ predicate on the "site" field.
func SiteEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldSite, v))
}

// SiteNEQ applies the NEQ predicate on the "site" field.
func SiteNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldSite, v))
}

// SiteIn applies the In predicate on the "site" field.
func SiteIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldSite, vs...))
}

// SiteNotIn applies the NotIn predicate on the "site" field.
func SiteNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldSite, vs...))
}

// SiteGT applies the GT predicate on the "site" field.
func SiteGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldSite, v))
}

// SiteGTE applies the GTE predicate on the "site" field.
func SiteGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldSite, v))
}

// SiteLT applies the LT predicate on the "site" field.
func SiteLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldSite, v))
}

// SiteLTE applies the LTE predicate on the "site" field.
func SiteLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldSite, v))
}

// SiteContains applies the Contains predicate on the "site" field.
func SiteContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldSite, v))
}

// SiteHasPrefix applies the HasPrefix predicate on the "site" field.
func SiteHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldSite, v))
}

// SiteHasSuffix applies the HasSuffix predicate on the "site" field.
func SiteHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldSite, v))
}

// SiteIsNil applies the IsNil predicate on the "site" field.
func SiteIsNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIsNull(FieldSite))
}

// SiteNotNil applies the NotNil predicate on the "site" field.
func SiteNotNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotNull(FieldSite))
}

// SiteEqualFold applies the EqualFold predicate on the "site" field.
func SiteEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldSite, v))
}

// SiteContainsFold applies the ContainsFold predicate on the "site" field.
func SiteContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldSite, v))
}

// CommandEQ applies the EQ predicate on the "command" field.
func CommandEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldCommand, v))
}

// CommandNEQ applies the NEQ predicate on the "command" field.
func CommandNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldCommand, v))
}

// CommandIn applies the In predicate on the "command" field.
func CommandIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldCommand, vs...))
}

// CommandNotIn applies the NotIn predicate on the "command" field.
func CommandNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldCommand, vs...))
}

// CommandGT applies the GT predicate on the "command" field.
func CommandGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldCommand, v))
}

// CommandGTE applies the GTE predicate on the "command" field.
func CommandGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldCommand, v))
}

// CommandLT applies the LT predicate on the "command" field.
func CommandLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldCommand, v))
}

// CommandLTE applies the LTE predicate on the "command" field.
func CommandLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldCommand, v))
}

// CommandContains applies the Contains predicate on the "command" field.
func CommandContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldCommand, v))
}

// CommandHasPrefix applies the HasPrefix predicate on the "command" field.
func CommandHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldCommand, v))
}

// CommandHasSuffix applies the HasSuffix predicate on the "command" field.
func CommandHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldCommand, v))
}

// CommandIsNil applies the IsNil predicate on the "command" field.
func CommandIsNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIsNull(FieldCommand))
}

// CommandNotNil applies the NotNil predicate on the "command" field.
func CommandNotNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotNull(FieldCommand))
}

// CommandEqualFold applies the EqualFold predicate on the "command" field.
func CommandEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldCommand, v))
}

// CommandContainsFold applies the ContainsFold predicate on the "command" field.
func CommandContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldCommand, v))
}

// RequestedByEQ applies the EQ predicate on the "requested_by" field.
func RequestedByEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldRequestedBy, v))
}

// RequestedByNEQ applies the NEQ predicate on the "requested_by" field.
func RequestedByNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldRequestedBy, v))
}

// RequestedByIn applies the In predicate on the "requested_by" field.
func RequestedByIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldRequestedBy, vs...))
}

// RequestedByNotIn applies the NotIn predicate on the "requested_by" field.
func RequestedByNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldRequestedBy, vs...))
}

// RequestedByGT applies the GT predicate on the "requested_by" field.
func RequestedByGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldRequestedBy, v))
}

// RequestedByGTE applies the GTE predicate on the "requested_by" field.
func RequestedByGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldRequestedBy, v))
}

// RequestedByLT applies the LT predicate on the "requested_by" field.
func RequestedByLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldRequestedBy, v))
}

// RequestedByLTE applies the LTE predicate on the "requested_by" field.
func RequestedByLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldRequestedBy, v))
}

// RequestedByContains applies the Contains predicate on the "requested_by" field.
func RequestedByContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldRequestedBy, v))
}

// RequestedByHasPrefix applies the HasPrefix predicate on the "requested_by" field.
func RequestedByHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldRequestedBy, v))
}

// RequestedByHasSuffix applies the HasSuffix predicate on the "requested_by" field.
func RequestedByHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldRequestedBy, v))
}

// RequestedByEqualFold applies the EqualFold predicate on the "requested_by" field.
func RequestedByEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldRequestedBy, v))
}

// RequestedByContainsFold applies the ContainsFold predicate on the "requested_by" field.
func RequestedByContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldRequestedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldStatus, vs...))
}

// ExitOkEQ applies the EQ predicate on the "exit_ok" field.
func ExitOkEQ(v bool) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldExitOk, v))
}

// ExitOkNEQ applies the NEQ predicate on the "exit_ok" field.
func ExitOkNEQ(v bool) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldExitOk, v))
}

// OutputEQ applies the EQ predicate on the "output" field.
func OutputEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldOutput, v))
}

// OutputNEQ applies the NEQ predicate on the "output" field.
func OutputNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldOutput, v))
}

// OutputIn applies the In predicate on the "output" field.
func OutputIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldOutput, vs...))
}

// OutputNotIn applies the NotIn predicate on the "output" field.
func OutputNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldOutput, vs...))
}

// OutputGT applies the GT predicate on the "output" field.
func OutputGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldOutput, v))
}

// OutputGTE applies the GTE predicate on the "output" field.
func OutputGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldOutput, v))
}

// OutputLT applies the LT predicate on the "output" field.
func OutputLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldOutput, v))
}

// OutputLTE applies the LTE predicate on the "output" field.
func OutputLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldOutput, v))
}

// OutputContains applies the Contains predicate on the "output" field.
func OutputContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldOutput, v))
}

// OutputHasPrefix applies the HasPrefix predicate on the "output" field.
func OutputHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldOutput, v))
}

// OutputHasSuffix applies the HasSuffix predicate on the "output" field.
func OutputHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldOutput, v))
}

// OutputIsNil applies the IsNil predicate on the "output" field.
func OutputIsNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIsNull(FieldOutput))
}

// OutputNotNil applies the NotNil predicate on the "output" field.
func OutputNotNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotNull(FieldOutput))
}

// OutputEqualFold applies the EqualFold predicate on the "output" field.
func OutputEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldOutput, v))
}

// OutputContainsFold applies the ContainsFold predicate on the "output" field.
func OutputContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldOutput, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldContainsFold(FieldError, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldDurationMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldCreatedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.ControlAction {
	return predicate.ControlAction(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.ControlAction {
	return predicate.ControlAction(sql.FieldNotNull(FieldFinishedAt))
}

// HasServer applies the HasEdge predicate on the "server" edge.
func HasServer() predicate.ControlAction {
	return predicate.ControlAction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerWith applies the HasEdge predicate on the "server" edge with a given conditions (other predicates).
func HasServerWith(preds ...predicate.Server) predicate.ControlAction {
	return predicate.ControlAction(func(s *sql.Selector) {
		step := newServerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ControlAction) predicate.ControlAction {
	return predicate.ControlAction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ControlAction) predicate.ControlAction {
	return predicate.ControlAction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ControlAction) predicate.ControlAction {
	return predicate.ControlAction(sql.NotPredicates(p))
}
