// Code generated by ent, DO NOT EDIT.

package server

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the server type in the database.
	Label = "server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldSSHUser holds the string denoting the ssh_user field in the database.
	FieldSSHUser = "ssh_user"
	// FieldSSHPort holds the string denoting the ssh_port field in the database.
	FieldSSHPort = "ssh_port"
	// FieldSSHKeyPath holds the string denoting the ssh_key_path field in the database.
	FieldSSHKeyPath = "ssh_key_path"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastPingedAt holds the string denoting the last_pinged_at field in the database.
	FieldLastPingedAt = "last_pinged_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the server in the database.
	Table = "servers"
)

// Columns holds all SQL columns for server fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldHostname,
	FieldSSHUser,
	FieldSSHPort,
	FieldSSHKeyPath,
	FieldLabels,
	FieldStatus,
	FieldLastPingedAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	HostnameValidator func(string) error
	// DefaultSSHUser holds the default value on creation for the "ssh_user" field.
	DefaultSSHUser string
	// DefaultSSHPort holds the default value on creation for the "ssh_port" field.
	DefaultSSHPort int
	// SSHPortValidator is a validator for the "ssh_port" field. It is called by the builders before save.
	SSHPortValidator func(int) error
	// SSHKeyPathValidator is a validator for the "ssh_key_path" field. It is called by the builders before save.
	SSHKeyPathValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnknown is the default value of the Status enum.
const DefaultStatus = StatusUnknown

// Status values.
const (
	StatusUnknown     Status = "unknown"
	StatusReachable   Status = "reachable"
	StatusUnreachable Status = "unreachable"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusUnknown, StatusReachable, StatusUnreachable:
		return nil
	default:
		return fmt.Errorf("server: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Server queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// BySSHUser orders the results by the ssh_user field.
func BySSHUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHUser, opts...).ToFunc()
}

// BySSHPort orders the results by the ssh_port field.
func BySSHPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHPort, opts...).ToFunc()
}

// BySSHKeyPath orders the results by the ssh_key_path field.
func BySSHKeyPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHKeyPath, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastPingedAt orders the results by the last_pinged_at field.
func ByLastPingedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPingedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
