// Code generated by ent, DO NOT EDIT.

package systemsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the systemsnapshot type in the database.
	Label = "system_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// EdgeServer holds the string denoting the server edge name in mutations.
	EdgeServer = "server"
	// Table holds the table name of the systemsnapshot in the database.
	Table = "system_snapshots"
	// ServerTable is the table that holds the server relation/edge.
	ServerTable = "system_snapshots"
	// ServerInverseTable is the table name for the Server entity.
	// It exists in this package in order to avoid circular dependency with the "server" package.
	ServerInverseTable = "servers"
	// ServerColumn is the table column denoting the server relation/edge.
	ServerColumn = "server_system_snapshot"
)

// Columns holds all SQL columns for systemsnapshot fields.
var Columns = []string{
	FieldID,
	FieldCapturedAt,
	FieldPayload,
	FieldLastError,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "system_snapshots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"server_system_snapshot",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCapturedAt holds the default value on creation for the "captured_at" field.
	DefaultCapturedAt func() time.Time
	// UpdateDefaultCapturedAt holds the default value on update for the "captured_at" field.
	UpdateDefaultCapturedAt func() time.Time
)

// OrderOption defines the ordering options for the SystemSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByServerField orders the results by server field.
func ByServerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServerStep(), sql.OrderByField(field, opts...))
	}
}
func newServerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ServerTable, ServerColumn),
	)
}
