// Code generated by ent, DO NOT EDIT.

package alertstate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the alertstate type in the database.
	Label = "alert_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRuleName holds the string denoting the rule_name field in the database.
	FieldRuleName = "rule_name"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldFirstFiredAt holds the string denoting the first_fired_at field in the database.
	FieldFirstFiredAt = "first_fired_at"
	// FieldLastNotifiedAt holds the string denoting the last_notified_at field in the database.
	FieldLastNotifiedAt = "last_notified_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the alertstate in the database.
	Table = "alert_states"
)

// Columns holds all SQL columns for alertstate fields.
var Columns = []string{
	FieldID,
	FieldRuleName,
	FieldFingerprint,
	FieldLabels,
	FieldStatus,
	FieldValue,
	FieldFirstFiredAt,
	FieldLastNotifiedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RuleNameValidator is a validator for the "rule_name" field. It is called by the builders before save.
	RuleNameValidator func(string) error
	// FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	FingerprintValidator func(string) error
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue float64
	// DefaultFirstFiredAt holds the default value on creation for the "first_fired_at" field.
	DefaultFirstFiredAt func() time.Time
	// DefaultLastNotifiedAt holds the default value on creation for the "last_notified_at" field.
	DefaultLastNotifiedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusFiring is the default value of the Status enum.
const DefaultStatus = StatusFiring

// Status values.
const (
	StatusFiring   Status = "firing"
	StatusResolved Status = "resolved"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusFiring, StatusResolved:
		return nil
	default:
		return fmt.Errorf("alertstate: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AlertState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRuleName orders the results by the rule_name field.
func ByRuleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleName, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByFirstFiredAt orders the results by the first_fired_at field.
func ByFirstFiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstFiredAt, opts...).ToFunc()
}

// ByLastNotifiedAt orders the results by the last_notified_at field.
func ByLastNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastNotifiedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
