// Code generated by ent, DO NOT EDIT.

package alertstate

import (
	"frappe-monitor/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldID, id))
}

// RuleName applies equality check predicate on the "rule_name" field. It's identical to RuleNameEQ.
func RuleName(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldRuleName, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldFingerprint, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldValue, v))
}

// FirstFiredAt applies equality check predicate on the "first_fired_at" field. It's identical to FirstFiredAtEQ.
func FirstFiredAt(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldFirstFiredAt, v))
}

// LastNotifiedAt applies equality check predicate on the "last_notified_at" field. It's identical to LastNotifiedAtEQ.
func LastNotifiedAt(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldLastNotifiedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldUpdatedAt, v))
}

// RuleNameEQ applies the EQ predicate on the "rule_name" field.
func RuleNameEQ(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldRuleName, v))
}

// RuleNameNEQ applies the NEQ predicate on the "rule_name" field.
func RuleNameNEQ(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldRuleName, v))
}

// RuleNameIn applies the In predicate on the "rule_name" field.
func RuleNameIn(vs ...string) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldRuleName, vs...))
}

// RuleNameNotIn applies the NotIn predicate on the "rule_name" field.
func RuleNameNotIn(vs ...string) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldRuleName, vs...))
}

// RuleNameGT applies the GT predicate on the "rule_name" field.
func RuleNameGT(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldRuleName, v))
}

// RuleNameGTE applies the GTE predicate on the "rule_name" field.
func RuleNameGTE(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldRuleName, v))
}

// RuleNameLT applies the LT predicate on the "rule_name" field.
func RuleNameLT(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldRuleName, v))
}

// RuleNameLTE applies the LTE predicate on the "rule_name" field.
func RuleNameLTE(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldRuleName, v))
}

// RuleNameContains applies the Contains predicate on the "rule_name" field.
func RuleNameContains(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldContains(FieldRuleName, v))
}

// RuleNameHasPrefix applies the HasPrefix predicate on the "rule_name" field.
func RuleNameHasPrefix(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldHasPrefix(FieldRuleName, v))
}

// RuleNameHasSuffix applies the HasSuffix predicate on the "rule_name" field.
func RuleNameHasSuffix(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldHasSuffix(FieldRuleName, v))
}

// RuleNameEqualFold applies the EqualFold predicate on the "rule_name" field.
func RuleNameEqualFold(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldEqualFold(FieldRuleName, v))
}

// RuleNameContainsFold applies the ContainsFold predicate on the "rule_name" field.
func RuleNameContainsFold(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldContainsFold(FieldRuleName, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.AlertState {
	return predicate.AlertState(sql.FieldContainsFold(FieldFingerprint, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.AlertState {
	return predicate.AlertState(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.AlertState {
	return predicate.AlertState(sql.FieldNotNull(FieldLabels))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldStatus, vs...))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldValue, v))
}

// FirstFiredAtEQ applies the EQ predicate on the "first_fired_at" field.
func FirstFiredAtEQ(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldFirstFiredAt, v))
}

// FirstFiredAtNEQ applies the NEQ predicate on the "first_fired_at" field.
func FirstFiredAtNEQ(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldFirstFiredAt, v))
}

// FirstFiredAtIn applies the In predicate on the "first_fired_at" field.
func FirstFiredAtIn(vs ...time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldFirstFiredAt, vs...))
}

// FirstFiredAtNotIn applies the NotIn predicate on the "first_fired_at" field.
func FirstFiredAtNotIn(vs ...time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldFirstFiredAt, vs...))
}

// FirstFiredAtGT applies the GT predicate on the "first_fired_at" field.
func FirstFiredAtGT(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldFirstFiredAt, v))
}

// FirstFiredAtGTE applies the GTE predicate on the "first_fired_at" field.
func FirstFiredAtGTE(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldFirstFiredAt, v))
}

// FirstFiredAtLT applies the LT predicate on the "first_fired_at" field.
func FirstFiredAtLT(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldFirstFiredAt, v))
}

// FirstFiredAtLTE applies the LTE predicate on the "first_fired_at" field.
func FirstFiredAtLTE(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldFirstFiredAt, v))
}

// LastNotifiedAtEQ applies the EQ predicate on the "last_notified_at" field.
func LastNotifiedAtEQ(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldLastNotifiedAt, v))
}

// LastNotifiedAtNEQ applies the NEQ predicate on the "last_notified_at" field.
func LastNotifiedAtNEQ(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldLastNotifiedAt, v))
}

// LastNotifiedAtIn applies the In predicate on the "last_notified_at" field.
func LastNotifiedAtIn(vs ...time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldLastNotifiedAt, vs...))
}

// LastNotifiedAtNotIn applies the NotIn predicate on the "last_notified_at" field.
func LastNotifiedAtNotIn(vs ...time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldLastNotifiedAt, vs...))
}

// LastNotifiedAtGT applies the GT predicate on the "last_notified_at" field.
func LastNotifiedAtGT(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldLastNotifiedAt, v))
}

// LastNotifiedAtGTE applies the GTE predicate on the "last_notified_at" field.
func LastNotifiedAtGTE(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldLastNotifiedAt, v))
}

// LastNotifiedAtLT applies the LT predicate on the "last_notified_at" field.
func LastNotifiedAtLT(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldLastNotifiedAt, v))
}

// LastNotifiedAtLTE applies the LTE predicate on the "last_notified_at" field.
func LastNotifiedAtLTE(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldLastNotifiedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AlertState {
	return predicate.AlertState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlertState) predicate.AlertState {
	return predicate.AlertState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlertState) predicate.AlertState {
	return predicate.AlertState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlertState) predicate.AlertState {
	return predicate.AlertState(sql.NotPredicates(p))
}
