// Code generated by ent, DO NOT EDIT.

package dbtarget

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dbtarget type in the database.
	Label = "db_target"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServerID holds the string denoting the server_id field in the database.
	FieldServerID = "server_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldLagThresholdSeconds holds the string denoting the lag_threshold_seconds field in the database.
	FieldLagThresholdSeconds = "lag_threshold_seconds"
	// FieldMysqlCommand holds the string denoting the mysql_command field in the database.
	FieldMysqlCommand = "mysql_command"
	// FieldDefaultsFile holds the string denoting the defaults_file field in the database.
	FieldDefaultsFile = "defaults_file"
	// FieldSocket holds the string denoting the socket field in the database.
	FieldSocket = "socket"
	// FieldHeartbeatEnabled holds the string denoting the heartbeat_enabled field in the database.
	FieldHeartbeatEnabled = "heartbeat_enabled"
	// FieldHeartbeatQuery holds the string denoting the heartbeat_query field in the database.
	FieldHeartbeatQuery = "heartbeat_query"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldLagSeconds holds the string denoting the lag_seconds field in the database.
	FieldLagSeconds = "lag_seconds"
	// FieldHeartbeatLagSeconds holds the string denoting the heartbeat_lag_seconds field in the database.
	FieldHeartbeatLagSeconds = "heartbeat_lag_seconds"
	// FieldIoRunning holds the string denoting the io_running field in the database.
	FieldIoRunning = "io_running"
	// FieldSQLRunning holds the string denoting the sql_running field in the database.
	FieldSQLRunning = "sql_running"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeServer holds the string denoting the server edge name in mutations.
	EdgeServer = "server"
	// Table holds the table name of the dbtarget in the database.
	Table = "db_targets"
	// ServerTable is the table that holds the server relation/edge.
	ServerTable = "db_targets"
	// ServerInverseTable is the table name for the Server entity.
	// It exists in this package in order to avoid circular dependency with the "server" package.
	ServerInverseTable = "servers"
	// ServerColumn is the table column denoting the server relation/edge.
	ServerColumn = "server_id"
)

// Columns holds all SQL columns for dbtarget fields.
var Columns = []string{
	FieldID,
	FieldServerID,
	FieldName,
	FieldEnabled,
	FieldLagThresholdSeconds,
	FieldMysqlCommand,
	FieldDefaultsFile,
	FieldSocket,
	FieldHeartbeatEnabled,
	FieldHeartbeatQuery,
	FieldStatus,
	FieldLastCheckedAt,
	FieldLagSeconds,
	FieldHeartbeatLagSeconds,
	FieldIoRunning,
	FieldSQLRunning,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultLagThresholdSeconds holds the default value on creation for the "lag_threshold_seconds" field.
	DefaultLagThresholdSeconds int
	// LagThresholdSecondsValidator is a validator for the "lag_threshold_seconds" field. It is called by the builders before save.
	LagThresholdSecondsValidator func(int) error
	// DefaultMysqlCommand holds the default value on creation for the "mysql_command" field.
	DefaultMysqlCommand string
	// DefaultHeartbeatEnabled holds the default value on creation for the "heartbeat_enabled" field.
	DefaultHeartbeatEnabled bool
	// DefaultIoRunning holds the default value on creation for the "io_running" field.
	DefaultIoRunning bool
	// DefaultSQLRunning holds the default value on creation for the "sql_running" field.
	DefaultSQLRunning bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnknown is the default value of the Status enum.
const DefaultStatus = StatusUnknown

// Status values.
const (
	StatusUnknown     Status = "unknown"
	StatusHealthy     Status = "healthy"
	StatusLagging     Status = "lagging"
	StatusBroken      Status = "broken"
	StatusUnreachable Status = "unreachable"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusUnknown, StatusHealthy, StatusLagging, StatusBroken, StatusUnreachable:
		return nil
	default:
		return fmt.Errorf("dbtarget: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the DBTarget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServerID orders the results by the server_id field.
func ByServerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLagThresholdSeconds orders the results by the lag_threshold_seconds field.
func ByLagThresholdSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLagThresholdSeconds, opts...).ToFunc()
}

// ByMysqlCommand orders the results by the mysql_command field.
func ByMysqlCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMysqlCommand, opts...).ToFunc()
}

// ByDefaultsFile orders the results by the defaults_file field.
func ByDefaultsFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultsFile, opts...).ToFunc()
}

// BySocket orders the results by the socket field.
func BySocket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSocket, opts...).ToFunc()
}

// ByHeartbeatEnabled orders the results by the heartbeat_enabled field.
func ByHeartbeatEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatEnabled, opts...).ToFunc()
}

// ByHeartbeatQuery orders the results by the heartbeat_query field.
func ByHeartbeatQuery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatQuery, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByLagSeconds orders the results by the lag_seconds field.
func ByLagSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLagSeconds, opts...).ToFunc()
}

// ByHeartbeatLagSeconds orders the results by the heartbeat_lag_seconds field.
func ByHeartbeatLagSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatLagSeconds, opts...).ToFunc()
}

// ByIoRunning orders the results by the io_running field.
func ByIoRunning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIoRunning, opts...).ToFunc()
}

// BySQLRunning orders the results by the sql_running field.
func BySQLRunning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSQLRunning, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByServerField orders the results by server field.
func ByServerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServerStep(), sql.OrderByField(field, opts...))
	}
}
func newServerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
	)
}
