// Code generated by ent, DO NOT EDIT.

package dbtarget

import (
	"frappe-monitor/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldID, id))
}

// ServerID applies equality check predicate on the "server_id" field. It's identical to ServerIDEQ.
func ServerID(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldServerID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldEnabled, v))
}

// LagThresholdSeconds applies equality check predicate on the "lag_threshold_seconds" field. It's identical to LagThresholdSecondsEQ.
func LagThresholdSeconds(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLagThresholdSeconds, v))
}

// ClientCommand applies equality check predicate on the "client_command" field. It's identical to ClientCommandEQ.
func ClientCommand(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldClientCommand, v))
}

// DefaultsFile applies equality check predicate on the "defaults_file" field. It's identical to DefaultsFileEQ.
func DefaultsFile(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldDefaultsFile, v))
}

// Socket applies equality check predicate on the "socket" field. It's identical to SocketEQ.
func Socket(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldSocket, v))
}

// HeartbeatEnabled applies equality check predicate on the "heartbeat_enabled" field. It's identical to HeartbeatEnabledEQ.
func HeartbeatEnabled(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldHeartbeatEnabled, v))
}

// HeartbeatQuery applies equality check predicate on the "heartbeat_query" field. It's identical to HeartbeatQueryEQ.
func HeartbeatQuery(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldHeartbeatQuery, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LagSeconds applies equality check predicate on the "lag_seconds" field. It's identical to LagSecondsEQ.
func LagSeconds(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLagSeconds, v))
}

// HeartbeatLagSeconds applies equality check predicate on the "heartbeat_lag_seconds" field. It's identical to HeartbeatLagSecondsEQ.
func HeartbeatLagSeconds(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldHeartbeatLagSeconds, v))
}

// IoRunning applies equality check predicate on the "io_running" field. It's identical to IoRunningEQ.
func IoRunning(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldIoRunning, v))
}

// SQLRunning applies equality check predicate on the "sql_running" field. It's identical to SQLRunningEQ.
func SQLRunning(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldSQLRunning, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// ServerIDEQ applies the EQ predicate on the "server_id" field.
func ServerIDEQ(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldServerID, v))
}

// ServerIDNEQ applies the NEQ predicate on the "server_id" field.
func ServerIDNEQ(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldServerID, v))
}

// ServerIDIn applies the In predicate on the "server_id" field.
func ServerIDIn(vs ...int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldServerID, vs...))
}

// ServerIDNotIn applies the NotIn predicate on the "server_id" field.
func ServerIDNotIn(vs ...int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldServerID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldEnabled, v))
}

// EngineEQ applies the EQ predicate on the "engine" field.
func EngineEQ(v Engine) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldEngine, v))
}

// EngineNEQ applies the NEQ predicate on the "engine" field.
func EngineNEQ(v Engine) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldEngine, v))
}

// EngineIn applies the In predicate on the "engine" field.
func EngineIn(vs ...Engine) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldEngine, vs...))
}

// EngineNotIn applies the NotIn predicate on the "engine" field.
func EngineNotIn(vs ...Engine) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldEngine, vs...))
}

// LagThresholdSecondsEQ applies the EQ predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsEQ(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLagThresholdSeconds, v))
}

// LagThresholdSecondsNEQ applies the NEQ predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsNEQ(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldLagThresholdSeconds, v))
}

// LagThresholdSecondsIn applies the In predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsIn(vs ...int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldLagThresholdSeconds, vs...))
}

// LagThresholdSecondsNotIn applies the NotIn predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsNotIn(vs ...int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldLagThresholdSeconds, vs...))
}

// LagThresholdSecondsGT applies the GT predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsGT(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldLagThresholdSeconds, v))
}

// LagThresholdSecondsGTE applies the GTE predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsGTE(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldLagThresholdSeconds, v))
}

// LagThresholdSecondsLT applies the LT predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsLT(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldLagThresholdSeconds, v))
}

// LagThresholdSecondsLTE applies the LTE predicate on the "lag_threshold_seconds" field.
func LagThresholdSecondsLTE(v int) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldLagThresholdSeconds, v))
}

// ClientCommandEQ applies the EQ predicate on the "client_command" field.
func ClientCommandEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldClientCommand, v))
}

// ClientCommandNEQ applies the NEQ predicate on the "client_command" field.
func ClientCommandNEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldClientCommand, v))
}

// ClientCommandIn applies the In predicate on the "client_command" field.
func ClientCommandIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldClientCommand, vs...))
}

// ClientCommandNotIn applies the NotIn predicate on the "client_command" field.
func ClientCommandNotIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldClientCommand, vs...))
}

// ClientCommandGT applies the GT predicate on the "client_command" field.
func ClientCommandGT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldClientCommand, v))
}

// ClientCommandGTE applies the GTE predicate on the "client_command" field.
func ClientCommandGTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldClientCommand, v))
}

// ClientCommandLT applies the LT predicate on the "client_command" field.
func ClientCommandLT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldClientCommand, v))
}

// ClientCommandLTE applies the LTE predicate on the "client_command" field.
func ClientCommandLTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldClientCommand, v))
}

// ClientCommandContains applies the Contains predicate on the "client_command" field.
func ClientCommandContains(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContains(FieldClientCommand, v))
}

// ClientCommandHasPrefix applies the HasPrefix predicate on the "client_command" field.
func ClientCommandHasPrefix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasPrefix(FieldClientCommand, v))
}

// ClientCommandHasSuffix applies the HasSuffix predicate on the "client_command" field.
func ClientCommandHasSuffix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasSuffix(FieldClientCommand, v))
}

// ClientCommandIsNil applies the IsNil predicate on the "client_command" field.
func ClientCommandIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldClientCommand))
}

// ClientCommandNotNil applies the NotNil predicate on the "client_command" field.
func ClientCommandNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldClientCommand))
}

// ClientCommandEqualFold applies the EqualFold predicate on the "client_command" field.
func ClientCommandEqualFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEqualFold(FieldClientCommand, v))
}

// ClientCommandContainsFold applies the ContainsFold predicate on the "client_command" field.
func ClientCommandContainsFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContainsFold(FieldClientCommand, v))
}

// DefaultsFileEQ applies the EQ predicate on the "defaults_file" field.
func DefaultsFileEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldDefaultsFile, v))
}

// DefaultsFileNEQ applies the NEQ predicate on the "defaults_file" field.
func DefaultsFileNEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldDefaultsFile, v))
}

// DefaultsFileIn applies the In predicate on the "defaults_file" field.
func DefaultsFileIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldDefaultsFile, vs...))
}

// DefaultsFileNotIn applies the NotIn predicate on the "defaults_file" field.
func DefaultsFileNotIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldDefaultsFile, vs...))
}

// DefaultsFileGT applies the GT predicate on the "defaults_file" field.
func DefaultsFileGT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldDefaultsFile, v))
}

// DefaultsFileGTE applies the GTE predicate on the "defaults_file" field.
func DefaultsFileGTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldDefaultsFile, v))
}

// DefaultsFileLT applies the LT predicate on the "defaults_file" field.
func DefaultsFileLT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldDefaultsFile, v))
}

// DefaultsFileLTE applies the LTE predicate on the "defaults_file" field.
func DefaultsFileLTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldDefaultsFile, v))
}

// DefaultsFileContains applies the Contains predicate on the "defaults_file" field.
func DefaultsFileContains(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContains(FieldDefaultsFile, v))
}

// DefaultsFileHasPrefix applies the HasPrefix predicate on the "defaults_file" field.
func DefaultsFileHasPrefix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasPrefix(FieldDefaultsFile, v))
}

// DefaultsFileHasSuffix applies the HasSuffix predicate on the "defaults_file" field.
func DefaultsFileHasSuffix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasSuffix(FieldDefaultsFile, v))
}

// DefaultsFileIsNil applies the IsNil predicate on the "defaults_file" field.
func DefaultsFileIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldDefaultsFile))
}

// DefaultsFileNotNil applies the NotNil predicate on the "defaults_file" field.
func DefaultsFileNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldDefaultsFile))
}

// DefaultsFileEqualFold applies the EqualFold predicate on the "defaults_file" field.
func DefaultsFileEqualFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEqualFold(FieldDefaultsFile, v))
}

// DefaultsFileContainsFold applies the ContainsFold predicate on the "defaults_file" field.
func DefaultsFileContainsFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContainsFold(FieldDefaultsFile, v))
}

// SocketEQ applies the EQ predicate on the "socket" field.
func SocketEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldSocket, v))
}

// SocketNEQ applies the NEQ predicate on the "socket" field.
func SocketNEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldSocket, v))
}

// SocketIn applies the In predicate on the "socket" field.
func SocketIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldSocket, vs...))
}

// SocketNotIn applies the NotIn predicate on the "socket" field.
func SocketNotIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldSocket, vs...))
}

// SocketGT applies the GT predicate on the "socket" field.
func SocketGT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldSocket, v))
}

// SocketGTE applies the GTE predicate on the "socket" field.
func SocketGTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldSocket, v))
}

// SocketLT applies the LT predicate on the "socket" field.
func SocketLT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldSocket, v))
}

// SocketLTE applies the LTE predicate on the "socket" field.
func SocketLTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldSocket, v))
}

// SocketContains applies the Contains predicate on the "socket" field.
func SocketContains(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContains(FieldSocket, v))
}

// SocketHasPrefix applies the HasPrefix predicate on the "socket" field.
func SocketHasPrefix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasPrefix(FieldSocket, v))
}

// SocketHasSuffix applies the HasSuffix predicate on the "socket" field.
func SocketHasSuffix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasSuffix(FieldSocket, v))
}

// SocketIsNil applies the IsNil predicate on the "socket" field.
func SocketIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldSocket))
}

// SocketNotNil applies the NotNil predicate on the "socket" field.
func SocketNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldSocket))
}

// SocketEqualFold applies the EqualFold predicate on the "socket" field.
func SocketEqualFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEqualFold(FieldSocket, v))
}

// SocketContainsFold applies the ContainsFold predicate on the "socket" field.
func SocketContainsFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContainsFold(FieldSocket, v))
}

// HeartbeatEnabledEQ applies the EQ predicate on the "heartbeat_enabled" field.
func HeartbeatEnabledEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldHeartbeatEnabled, v))
}

// HeartbeatEnabledNEQ applies the NEQ predicate on the "heartbeat_enabled" field.
func HeartbeatEnabledNEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldHeartbeatEnabled, v))
}

// HeartbeatQueryEQ applies the EQ predicate on the "heartbeat_query" field.
func HeartbeatQueryEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldHeartbeatQuery, v))
}

// HeartbeatQueryNEQ applies the NEQ predicate on the "heartbeat_query" field.
func HeartbeatQueryNEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldHeartbeatQuery, v))
}

// HeartbeatQueryIn applies the In predicate on the "heartbeat_query" field.
func HeartbeatQueryIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldHeartbeatQuery, vs...))
}

// HeartbeatQueryNotIn applies the NotIn predicate on the "heartbeat_query" field.
func HeartbeatQueryNotIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldHeartbeatQuery, vs...))
}

// HeartbeatQueryGT applies the GT predicate on the "heartbeat_query" field.
func HeartbeatQueryGT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldHeartbeatQuery, v))
}

// HeartbeatQueryGTE applies the GTE predicate on the "heartbeat_query" field.
func HeartbeatQueryGTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldHeartbeatQuery, v))
}

// HeartbeatQueryLT applies the LT predicate on the "heartbeat_query" field.
func HeartbeatQueryLT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldHeartbeatQuery, v))
}

// HeartbeatQueryLTE applies the LTE predicate on the "heartbeat_query" field.
func HeartbeatQueryLTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldHeartbeatQuery, v))
}

// HeartbeatQueryContains applies the Contains predicate on the "heartbeat_query" field.
func HeartbeatQueryContains(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContains(FieldHeartbeatQuery, v))
}

// HeartbeatQueryHasPrefix applies the HasPrefix predicate on the "heartbeat_query" field.
func HeartbeatQueryHasPrefix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasPrefix(FieldHeartbeatQuery, v))
}

// HeartbeatQueryHasSuffix applies the HasSuffix predicate on the "heartbeat_query" field.
func HeartbeatQueryHasSuffix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasSuffix(FieldHeartbeatQuery, v))
}

// HeartbeatQueryIsNil applies the IsNil predicate on the "heartbeat_query" field.
func HeartbeatQueryIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldHeartbeatQuery))
}

// HeartbeatQueryNotNil applies the NotNil predicate on the "heartbeat_query" field.
func HeartbeatQueryNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldHeartbeatQuery))
}

// HeartbeatQueryEqualFold applies the EqualFold predicate on the "heartbeat_query" field.
func HeartbeatQueryEqualFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEqualFold(FieldHeartbeatQuery, v))
}

// HeartbeatQueryContainsFold applies the ContainsFold predicate on the "heartbeat_query" field.
func HeartbeatQueryContainsFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContainsFold(FieldHeartbeatQuery, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldStatus, vs...))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldLastCheckedAt))
}

// LagSecondsEQ applies the EQ predicate on the "lag_seconds" field.
func LagSecondsEQ(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLagSeconds, v))
}

// LagSecondsNEQ applies the NEQ predicate on the "lag_seconds" field.
func LagSecondsNEQ(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldLagSeconds, v))
}

// LagSecondsIn applies the In predicate on the "lag_seconds" field.
func LagSecondsIn(vs ...int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldLagSeconds, vs...))
}

// LagSecondsNotIn applies the NotIn predicate on the "lag_seconds" field.
func LagSecondsNotIn(vs ...int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldLagSeconds, vs...))
}

// LagSecondsGT applies the GT predicate on the "lag_seconds" field.
func LagSecondsGT(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldLagSeconds, v))
}

// LagSecondsGTE applies the GTE predicate on the "lag_seconds" field.
func LagSecondsGTE(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldLagSeconds, v))
}

// LagSecondsLT applies the LT predicate on the "lag_seconds" field.
func LagSecondsLT(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldLagSeconds, v))
}

// LagSecondsLTE applies the LTE predicate on the "lag_seconds" field.
func LagSecondsLTE(v int64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldLagSeconds, v))
}

// LagSecondsIsNil applies the IsNil predicate on the "lag_seconds" field.
func LagSecondsIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldLagSeconds))
}

// LagSecondsNotNil applies the NotNil predicate on the "lag_seconds" field.
func LagSecondsNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldLagSeconds))
}

// HeartbeatLagSecondsEQ applies the EQ predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsEQ(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldHeartbeatLagSeconds, v))
}

// HeartbeatLagSecondsNEQ applies the NEQ predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsNEQ(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldHeartbeatLagSeconds, v))
}

// HeartbeatLagSecondsIn applies the In predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsIn(vs ...float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldHeartbeatLagSeconds, vs...))
}

// HeartbeatLagSecondsNotIn applies the NotIn predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsNotIn(vs ...float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldHeartbeatLagSeconds, vs...))
}

// HeartbeatLagSecondsGT applies the GT predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsGT(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldHeartbeatLagSeconds, v))
}

// HeartbeatLagSecondsGTE applies the GTE predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsGTE(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldHeartbeatLagSeconds, v))
}

// HeartbeatLagSecondsLT applies the LT predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsLT(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldHeartbeatLagSeconds, v))
}

// HeartbeatLagSecondsLTE applies the LTE predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsLTE(v float64) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldHeartbeatLagSeconds, v))
}

// HeartbeatLagSecondsIsNil applies the IsNil predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldHeartbeatLagSeconds))
}

// HeartbeatLagSecondsNotNil applies the NotNil predicate on the "heartbeat_lag_seconds" field.
func HeartbeatLagSecondsNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldHeartbeatLagSeconds))
}

// IoRunningEQ applies the EQ predicate on the "io_running" field.
func IoRunningEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldIoRunning, v))
}

// IoRunningNEQ applies the NEQ predicate on the "io_running" field.
func IoRunningNEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldIoRunning, v))
}

// SQLRunningEQ applies the EQ predicate on the "sql_running" field.
func SQLRunningEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldSQLRunning, v))
}

// SQLRunningNEQ applies the NEQ predicate on the "sql_running" field.
func SQLRunningNEQ(v bool) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldSQLRunning, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DBTarget {
	return predicate.DBTarget(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasServer applies the HasEdge predicate on the "server" edge.
func HasServer() predicate.DBTarget {
	return predicate.DBTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerTable, ServerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerWith applies the HasEdge predicate on the "server" edge with a given conditions (other predicates).
func HasServerWith(preds ...predicate.Server) predicate.DBTarget {
	return predicate.DBTarget(func(s *sql.Selector) {
		step := newServerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DBTarget) predicate.DBTarget {
	return predicate.DBTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DBTarget) predicate.DBTarget {
	return predicate.DBTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DBTarget) predicate.DBTarget {
	return predicate.DBTarget(sql.NotPredicates(p))
}
