// Package installer implements the cross-platform `frappe-monitor install`
// command. One Go codebase handles Windows, Linux, and macOS: it lays the
// (self-contained, UI-embedded) binary and a generated config into an operator-
// chosen root directory, and emits a service definition for the chosen process
// manager (systemd / launchd / supervisor / PM2). Nothing here is OS-specific
// at compile time — behaviour branches on Options.GOOS so it is fully testable.
package installer

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// Service managers the installer can generate a definition for.
const (
	ServiceSystemd    = "systemd"
	ServiceLaunchd    = "launchd"
	ServiceSupervisor = "supervisor"
	ServicePM2        = "pm2"
	ServiceNone       = "none"
)

// Options is the fully-resolved install request (after flags + prompts).
type Options struct {
	Root       string // install root directory
	ListenAddr string // e.g. ":8080" or "127.0.0.1:8080"

	// Database.
	DBDriver   string // mariadb | mysql | postgres | sqlite
	DBHost     string
	DBPort     int
	DBUser     string
	DBPassword string
	DBName     string
	DBSSLMode  string // postgres
	DBPath     string // sqlite

	AuthPassword string

	Service string // one of the Service* constants
	GOOS    string // target OS; defaults to runtime.GOOS

	// SourceBinary is the path to the binary to install (defaults to the
	// running executable).
	SourceBinary string
}

func (o Options) goos() string {
	if o.GOOS != "" {
		return o.GOOS
	}
	return runtime.GOOS
}

// DefaultRoot returns the conventional install directory for an OS.
func DefaultRoot(goos string) string {
	switch goos {
	case "windows":
		base := os.Getenv("ProgramData")
		if base == "" {
			base = `C:\ProgramData`
		}
		return filepath.Join(base, "frappe-monitor")
	case "linux":
		return "/opt/frappe-monitor"
	default: // darwin + anything else: user-space
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".frappe-monitor")
		}
		return "/opt/frappe-monitor"
	}
}

// DefaultService returns the natural process manager for an OS.
func DefaultService(goos string) string {
	switch goos {
	case "linux":
		return ServiceSystemd
	case "darwin":
		return ServiceLaunchd
	case "windows":
		return ServicePM2 // systemd/launchd absent; PM2 runs cross-platform
	default:
		return ServiceNone
	}
}

// BinaryName is the installed binary filename for an OS.
func BinaryName(goos string) string {
	if goos == "windows" {
		return "frappe-monitor.exe"
	}
	return "frappe-monitor"
}

// BinaryPath / ConfigPath / LogPath are the canonical locations under Root.
func (o Options) BinaryPath() string { return filepath.Join(o.Root, "bin", BinaryName(o.goos())) }
func (o Options) ConfigPath() string { return filepath.Join(o.Root, "monitor.yaml") }
func (o Options) LogPath() string    { return filepath.Join(o.Root, "logs", "monitor.log") }

// normalizedDriver collapses aliases for config + DSN consistency.
func normalizedDriver(d string) string {
	switch strings.ToLower(strings.TrimSpace(d)) {
	case "", "sqlite", "sqlite3":
		return "sqlite"
	case "mysql", "mariadb":
		return "mariadb"
	case "postgres", "postgresql", "pg":
		return "postgres"
	default:
		return strings.ToLower(strings.TrimSpace(d))
	}
}

// RenderConfig produces the monitor.yaml for these options. Missing engine
// fields fall back to engine defaults at runtime; the app fills unspecified
// blocks from its own defaults().
func RenderConfig(o Options) string {
	drv := normalizedDriver(o.DBDriver)
	var db strings.Builder
	fmt.Fprintf(&db, "  driver: %s\n", yamlStr(drv))
	switch drv {
	case "sqlite":
		path := o.DBPath
		if path == "" {
			path = filepath.ToSlash(filepath.Join(o.Root, "data", "monitor.db"))
		}
		fmt.Fprintf(&db, "  path: %s\n", yamlStr(path))
	default: // mariadb / postgres
		fmt.Fprintf(&db, "  host: %s\n", yamlStr(orStr(o.DBHost, "127.0.0.1")))
		fmt.Fprintf(&db, "  port: %d\n", o.DBPort)
		fmt.Fprintf(&db, "  user: %s\n", yamlStr(o.DBUser))
		fmt.Fprintf(&db, "  password: %s\n", yamlStr(o.DBPassword))
		fmt.Fprintf(&db, "  name: %s\n", yamlStr(o.DBName))
		if drv == "postgres" {
			fmt.Fprintf(&db, "  sslmode: %s\n", yamlStr(orStr(o.DBSSLMode, "disable")))
		}
		fmt.Fprintf(&db, "  max_open_conns: 20\n  max_idle_conns: 5\n")
	}

	return fmt.Sprintf(`# frappe-monitor configuration — generated by 'frappe-monitor install'.
# Edit any value and restart the service to apply.

server:
  listen_addr: %s
  read_timeout_seconds: 15
  write_timeout_seconds: 15

database:
%s
ssh:
  dial_timeout_seconds: 10
  command_timeout_seconds: 30
  max_connections_per_host: 2

log:
  level: "info"
  format: "json"

metrics:
  vm_url: "http://127.0.0.1:8428"
  push_timeout_seconds: 5
  query_timeout_seconds: 15

logs:
  loki_url: "http://127.0.0.1:3100"
  push_timeout_seconds: 5
  query_timeout_seconds: 15

scheduler:
  default_interval_seconds: 900
  max_parallel: 10
  per_job_timeout_seconds: 30

auth:
  password: %s
  realm: "frappe-monitor"

alerts:
  enabled: false

realtime:
  enabled: true
  ping_interval_seconds: 30
  write_timeout_seconds: 10
  send_buffer: 128
  max_clients: 512
`, yamlStr(orStr(o.ListenAddr, ":8080")), db.String(), yamlStr(o.AuthPassword))
}

// Install lays out the root directory, copies the binary, writes the config,
// and (when a manager is selected) writes the service file — printing the
// exact commands to enable it. It never performs privileged operations
// implicitly; system-level registration is printed for the operator to run.
func Install(o Options, out io.Writer) error {
	if o.Root == "" {
		return fmt.Errorf("install root is required")
	}
	if o.AuthPassword == "" {
		return fmt.Errorf("a dashboard password is required (auth.password)")
	}

	for _, d := range []string{
		filepath.Join(o.Root, "bin"),
		filepath.Join(o.Root, "data"),
		filepath.Join(o.Root, "logs"),
	} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", d, err)
		}
	}

	src := o.SourceBinary
	if src == "" {
		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("locate running binary: %w", err)
		}
		src = exe
	}
	if err := copyFile(src, o.BinaryPath(), 0o755); err != nil {
		return fmt.Errorf("install binary: %w", err)
	}
	fmt.Fprintf(out, "  installed binary  -> %s\n", o.BinaryPath())

	// Config: never clobber an existing one (preserve operator edits on upgrade).
	if _, err := os.Stat(o.ConfigPath()); os.IsNotExist(err) {
		if err := writeFile(o.ConfigPath(), []byte(RenderConfig(o)), 0o600); err != nil {
			return fmt.Errorf("write config: %w", err)
		}
		fmt.Fprintf(out, "  wrote config      -> %s\n", o.ConfigPath())
	} else {
		fmt.Fprintf(out, "  kept existing config -> %s\n", o.ConfigPath())
	}

	if o.Service != "" && o.Service != ServiceNone {
		name, content, hint, err := ServiceFile(o)
		if err != nil {
			return err
		}
		dst := filepath.Join(o.Root, name)
		if err := writeFile(dst, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write service file: %w", err)
		}
		fmt.Fprintf(out, "  wrote %s service -> %s\n", o.Service, dst)
		fmt.Fprintf(out, "\nTo enable it:\n%s\n", hint)
	}

	fmt.Fprintf(out, "\nDone. Run directly with:\n  %s --config %s\n", o.BinaryPath(), o.ConfigPath())
	return nil
}

func copyFile(src, dst string, mode os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	tmp := dst + ".new"
	out, err := os.OpenFile(tmp, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, mode)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	if err := out.Close(); err != nil {
		return err
	}
	// Atomic swap so a half-copied binary never runs.
	return os.Rename(tmp, dst)
}

func writeFile(path string, data []byte, mode os.FileMode) error {
	return os.WriteFile(path, data, mode)
}

func orStr(s, def string) string {
	if strings.TrimSpace(s) == "" {
		return def
	}
	return s
}

// yamlStr renders a Go string as a safe double-quoted YAML scalar.
func yamlStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
