// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LogCursorsColumns holds the columns for the "log_cursors" table.
	LogCursorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "log_path", Type: field.TypeString},
		{Name: "byte_offset", Type: field.TypeInt64, Default: 0},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "server_log_cursors", Type: field.TypeInt},
	}
	// LogCursorsTable holds the schema information for the "log_cursors" table.
	LogCursorsTable = &schema.Table{
		Name:       "log_cursors",
		Columns:    LogCursorsColumns,
		PrimaryKey: []*schema.Column{LogCursorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "log_cursors_servers_log_cursors",
				Columns:    []*schema.Column{LogCursorsColumns[4]},
				RefColumns: []*schema.Column{ServersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "logcursor_log_path_server_log_cursors",
				Unique:  true,
				Columns: []*schema.Column{LogCursorsColumns[1], LogCursorsColumns[4]},
			},
		},
	}
	// ServersColumns holds the columns for the "servers" table.
	ServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "hostname", Type: field.TypeString, Unique: true},
		{Name: "ssh_user", Type: field.TypeString, Default: "monitor"},
		{Name: "ssh_port", Type: field.TypeInt, Default: 22},
		{Name: "ssh_key_path", Type: field.TypeString},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"unknown", "reachable", "unreachable"}, Default: "unknown"},
		{Name: "last_pinged_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ServersTable holds the schema information for the "servers" table.
	ServersTable = &schema.Table{
		Name:       "servers",
		Columns:    ServersColumns,
		PrimaryKey: []*schema.Column{ServersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LogCursorsTable,
		ServersTable,
	}
)

func init() {
	LogCursorsTable.ForeignKeys[0].RefTable = ServersTable
}
