// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/alertstate"
	"frappe-monitor/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlertStateUpdate is the builder for updating AlertState entities.
type AlertStateUpdate struct {
	config
	hooks    []Hook
	mutation *AlertStateMutation
}

// Where appends a list predicates to the AlertStateUpdate builder.
func (_u *AlertStateUpdate) Where(ps ...predicate.AlertState) *AlertStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRuleName sets the "rule_name" field.
func (_u *AlertStateUpdate) SetRuleName(v string) *AlertStateUpdate {
	_u.mutation.SetRuleName(v)
	return _u
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (_u *AlertStateUpdate) SetNillableRuleName(v *string) *AlertStateUpdate {
	if v != nil {
		_u.SetRuleName(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *AlertStateUpdate) SetFingerprint(v string) *AlertStateUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *AlertStateUpdate) SetNillableFingerprint(v *string) *AlertStateUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *AlertStateUpdate) SetLabels(v map[string]string) *AlertStateUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *AlertStateUpdate) ClearLabels() *AlertStateUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AlertStateUpdate) SetStatus(v alertstate.Status) *AlertStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AlertStateUpdate) SetNillableStatus(v *alertstate.Status) *AlertStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *AlertStateUpdate) SetValue(v float64) *AlertStateUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *AlertStateUpdate) SetNillableValue(v *float64) *AlertStateUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *AlertStateUpdate) AddValue(v float64) *AlertStateUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *AlertStateUpdate) SetLastNotifiedAt(v time.Time) *AlertStateUpdate {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *AlertStateUpdate) SetNillableLastNotifiedAt(v *time.Time) *AlertStateUpdate {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertStateUpdate) SetUpdatedAt(v time.Time) *AlertStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AlertStateMutation object of the builder.
func (_u *AlertStateUpdate) Mutation() *AlertStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alertstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlertStateUpdate) check() error {
	if v, ok := _u.mutation.RuleName(); ok {
		if err := alertstate.RuleNameValidator(v); err != nil {
			return &ValidationError{Name: "rule_name", err: fmt.Errorf(`ent: validator failed for field "AlertState.rule_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fingerprint(); ok {
		if err := alertstate.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "AlertState.fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := alertstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertState.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AlertStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alertstate.Table, alertstate.Columns, sqlgraph.NewFieldSpec(alertstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuleName(); ok {
		_spec.SetField(alertstate.FieldRuleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(alertstate.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(alertstate.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(alertstate.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(alertstate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(alertstate.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(alertstate.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(alertstate.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alertstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertStateUpdateOne is the builder for updating a single AlertState entity.
type AlertStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertStateMutation
}

// SetRuleName sets the "rule_name" field.
func (_u *AlertStateUpdateOne) SetRuleName(v string) *AlertStateUpdateOne {
	_u.mutation.SetRuleName(v)
	return _u
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (_u *AlertStateUpdateOne) SetNillableRuleName(v *string) *AlertStateUpdateOne {
	if v != nil {
		_u.SetRuleName(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *AlertStateUpdateOne) SetFingerprint(v string) *AlertStateUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *AlertStateUpdateOne) SetNillableFingerprint(v *string) *AlertStateUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *AlertStateUpdateOne) SetLabels(v map[string]string) *AlertStateUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *AlertStateUpdateOne) ClearLabels() *AlertStateUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AlertStateUpdateOne) SetStatus(v alertstate.Status) *AlertStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AlertStateUpdateOne) SetNillableStatus(v *alertstate.Status) *AlertStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *AlertStateUpdateOne) SetValue(v float64) *AlertStateUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *AlertStateUpdateOne) SetNillableValue(v *float64) *AlertStateUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *AlertStateUpdateOne) AddValue(v float64) *AlertStateUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *AlertStateUpdateOne) SetLastNotifiedAt(v time.Time) *AlertStateUpdateOne {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *AlertStateUpdateOne) SetNillableLastNotifiedAt(v *time.Time) *AlertStateUpdateOne {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertStateUpdateOne) SetUpdatedAt(v time.Time) *AlertStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AlertStateMutation object of the builder.
func (_u *AlertStateUpdateOne) Mutation() *AlertStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the AlertStateUpdate builder.
func (_u *AlertStateUpdateOne) Where(ps ...predicate.AlertState) *AlertStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertStateUpdateOne) Select(field string, fields ...string) *AlertStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AlertState entity.
func (_u *AlertStateUpdateOne) Save(ctx context.Context) (*AlertState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertStateUpdateOne) SaveX(ctx context.Context) *AlertState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alertstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlertStateUpdateOne) check() error {
	if v, ok := _u.mutation.RuleName(); ok {
		if err := alertstate.RuleNameValidator(v); err != nil {
			return &ValidationError{Name: "rule_name", err: fmt.Errorf(`ent: validator failed for field "AlertState.rule_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fingerprint(); ok {
		if err := alertstate.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "AlertState.fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := alertstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertState.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AlertStateUpdateOne) sqlSave(ctx context.Context) (_node *AlertState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alertstate.Table, alertstate.Columns, sqlgraph.NewFieldSpec(alertstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AlertState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alertstate.FieldID)
		for _, f := range fields {
			if !alertstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alertstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuleName(); ok {
		_spec.SetField(alertstate.FieldRuleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(alertstate.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(alertstate.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(alertstate.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(alertstate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(alertstate.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(alertstate.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(alertstate.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alertstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AlertState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
