// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"frappe-monitor/ent/alertstate"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AlertState is the model entity for the AlertState schema.
type AlertState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RuleName holds the value of the "rule_name" field.
	RuleName string `json:"rule_name,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// Labels holds the value of the "labels" field.
	Labels map[string]string `json:"labels,omitempty"`
	// Status holds the value of the "status" field.
	Status alertstate.Status `json:"status,omitempty"`
	// Value holds the value of the "value" field.
	Value float64 `json:"value,omitempty"`
	// FirstFiredAt holds the value of the "first_fired_at" field.
	FirstFiredAt time.Time `json:"first_fired_at,omitempty"`
	// LastNotifiedAt holds the value of the "last_notified_at" field.
	LastNotifiedAt time.Time `json:"last_notified_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertstate.FieldLabels:
			values[i] = new([]byte)
		case alertstate.FieldValue:
			values[i] = new(sql.NullFloat64)
		case alertstate.FieldID:
			values[i] = new(sql.NullInt64)
		case alertstate.FieldRuleName, alertstate.FieldFingerprint, alertstate.FieldStatus:
			values[i] = new(sql.NullString)
		case alertstate.FieldFirstFiredAt, alertstate.FieldLastNotifiedAt, alertstate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertState fields.
func (_m *AlertState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case alertstate.FieldRuleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_name", values[i])
			} else if value.Valid {
				_m.RuleName = value.String
			}
		case alertstate.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case alertstate.FieldLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Labels); err != nil {
					return fmt.Errorf("unmarshal field labels: %w", err)
				}
			}
		case alertstate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = alertstate.Status(value.String)
			}
		case alertstate.FieldValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.Float64
			}
		case alertstate.FieldFirstFiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_fired_at", values[i])
			} else if value.Valid {
				_m.FirstFiredAt = value.Time
			}
		case alertstate.FieldLastNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_notified_at", values[i])
			} else if value.Valid {
				_m.LastNotifiedAt = value.Time
			}
		case alertstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the AlertState.
// This includes values selected through modifiers, order, etc.
func (_m *AlertState) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AlertState.
// Note that you need to call AlertState.Unwrap() before calling this method if this AlertState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlertState) Update() *AlertStateUpdateOne {
	return NewAlertStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlertState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlertState) Unwrap() *AlertState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlertState) String() string {
	var builder strings.Builder
	builder.WriteString("AlertState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rule_name=")
	builder.WriteString(_m.RuleName)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("first_fired_at=")
	builder.WriteString(_m.FirstFiredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_notified_at=")
	builder.WriteString(_m.LastNotifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AlertStates is a parsable slice of AlertState.
type AlertStates []*AlertState
