// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/alertstate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlertStateCreate is the builder for creating a AlertState entity.
type AlertStateCreate struct {
	config
	mutation *AlertStateMutation
	hooks    []Hook
}

// SetRuleName sets the "rule_name" field.
func (_c *AlertStateCreate) SetRuleName(v string) *AlertStateCreate {
	_c.mutation.SetRuleName(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *AlertStateCreate) SetFingerprint(v string) *AlertStateCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetLabels sets the "labels" field.
func (_c *AlertStateCreate) SetLabels(v map[string]string) *AlertStateCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AlertStateCreate) SetStatus(v alertstate.Status) *AlertStateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AlertStateCreate) SetNillableStatus(v *alertstate.Status) *AlertStateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *AlertStateCreate) SetValue(v float64) *AlertStateCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *AlertStateCreate) SetNillableValue(v *float64) *AlertStateCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetFirstFiredAt sets the "first_fired_at" field.
func (_c *AlertStateCreate) SetFirstFiredAt(v time.Time) *AlertStateCreate {
	_c.mutation.SetFirstFiredAt(v)
	return _c
}

// SetNillableFirstFiredAt sets the "first_fired_at" field if the given value is not nil.
func (_c *AlertStateCreate) SetNillableFirstFiredAt(v *time.Time) *AlertStateCreate {
	if v != nil {
		_c.SetFirstFiredAt(*v)
	}
	return _c
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_c *AlertStateCreate) SetLastNotifiedAt(v time.Time) *AlertStateCreate {
	_c.mutation.SetLastNotifiedAt(v)
	return _c
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_c *AlertStateCreate) SetNillableLastNotifiedAt(v *time.Time) *AlertStateCreate {
	if v != nil {
		_c.SetLastNotifiedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AlertStateCreate) SetUpdatedAt(v time.Time) *AlertStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AlertStateCreate) SetNillableUpdatedAt(v *time.Time) *AlertStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AlertStateMutation object of the builder.
func (_c *AlertStateCreate) Mutation() *AlertStateMutation {
	return _c.mutation
}

// Save creates the AlertState in the database.
func (_c *AlertStateCreate) Save(ctx context.Context) (*AlertState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertStateCreate) SaveX(ctx context.Context) *AlertState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertStateCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := alertstate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Value(); !ok {
		v := alertstate.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.FirstFiredAt(); !ok {
		v := alertstate.DefaultFirstFiredAt()
		_c.mutation.SetFirstFiredAt(v)
	}
	if _, ok := _c.mutation.LastNotifiedAt(); !ok {
		v := alertstate.DefaultLastNotifiedAt()
		_c.mutation.SetLastNotifiedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := alertstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertStateCreate) check() error {
	if _, ok := _c.mutation.RuleName(); !ok {
		return &ValidationError{Name: "rule_name", err: errors.New(`ent: missing required field "AlertState.rule_name"`)}
	}
	if v, ok := _c.mutation.RuleName(); ok {
		if err := alertstate.RuleNameValidator(v); err != nil {
			return &ValidationError{Name: "rule_name", err: fmt.Errorf(`ent: validator failed for field "AlertState.rule_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "AlertState.fingerprint"`)}
	}
	if v, ok := _c.mutation.Fingerprint(); ok {
		if err := alertstate.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "AlertState.fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AlertState.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := alertstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertState.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "AlertState.value"`)}
	}
	if _, ok := _c.mutation.FirstFiredAt(); !ok {
		return &ValidationError{Name: "first_fired_at", err: errors.New(`ent: missing required field "AlertState.first_fired_at"`)}
	}
	if _, ok := _c.mutation.LastNotifiedAt(); !ok {
		return &ValidationError{Name: "last_notified_at", err: errors.New(`ent: missing required field "AlertState.last_notified_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AlertState.updated_at"`)}
	}
	return nil
}

func (_c *AlertStateCreate) sqlSave(ctx context.Context) (*AlertState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertStateCreate) createSpec() (*AlertState, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alertstate.Table, sqlgraph.NewFieldSpec(alertstate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RuleName(); ok {
		_spec.SetField(alertstate.FieldRuleName, field.TypeString, value)
		_node.RuleName = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(alertstate.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(alertstate.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(alertstate.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(alertstate.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.FirstFiredAt(); ok {
		_spec.SetField(alertstate.FieldFirstFiredAt, field.TypeTime, value)
		_node.FirstFiredAt = value
	}
	if value, ok := _c.mutation.LastNotifiedAt(); ok {
		_spec.SetField(alertstate.FieldLastNotifiedAt, field.TypeTime, value)
		_node.LastNotifiedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(alertstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AlertStateCreateBulk is the builder for creating many AlertState entities in bulk.
type AlertStateCreateBulk struct {
	config
	err      error
	builders []*AlertStateCreate
}

// Save creates the AlertState entities in the database.
func (_c *AlertStateCreateBulk) Save(ctx context.Context) ([]*AlertState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlertState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertStateCreateBulk) SaveX(ctx context.Context) []*AlertState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
