// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"frappe-monitor/ent/controlaction"
	"frappe-monitor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ControlActionDelete is the builder for deleting a ControlAction entity.
type ControlActionDelete struct {
	config
	hooks    []Hook
	mutation *ControlActionMutation
}

// Where appends a list predicates to the ControlActionDelete builder.
func (_d *ControlActionDelete) Where(ps ...predicate.ControlAction) *ControlActionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ControlActionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ControlActionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ControlActionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(controlaction.Table, sqlgraph.NewFieldSpec(controlaction.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ControlActionDeleteOne is the builder for deleting a single ControlAction entity.
type ControlActionDeleteOne struct {
	_d *ControlActionDelete
}

// Where appends a list predicates to the ControlActionDelete builder.
func (_d *ControlActionDeleteOne) Where(ps ...predicate.ControlAction) *ControlActionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ControlActionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{controlaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ControlActionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
