// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/controlaction"
	"frappe-monitor/ent/predicate"
	"frappe-monitor/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ControlActionUpdate is the builder for updating ControlAction entities.
type ControlActionUpdate struct {
	config
	hooks    []Hook
	mutation *ControlActionMutation
}

// Where appends a list predicates to the ControlActionUpdate builder.
func (_u *ControlActionUpdate) Where(ps ...predicate.ControlAction) *ControlActionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServerID sets the "server_id" field.
func (_u *ControlActionUpdate) SetServerID(v int) *ControlActionUpdate {
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableServerID(v *int) *ControlActionUpdate {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *ControlActionUpdate) SetAction(v string) *ControlActionUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableAction(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetBenchPath sets the "bench_path" field.
func (_u *ControlActionUpdate) SetBenchPath(v string) *ControlActionUpdate {
	_u.mutation.SetBenchPath(v)
	return _u
}

// SetNillableBenchPath sets the "bench_path" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableBenchPath(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetBenchPath(*v)
	}
	return _u
}

// ClearBenchPath clears the value of the "bench_path" field.
func (_u *ControlActionUpdate) ClearBenchPath() *ControlActionUpdate {
	_u.mutation.ClearBenchPath()
	return _u
}

// SetSite sets the "site" field.
func (_u *ControlActionUpdate) SetSite(v string) *ControlActionUpdate {
	_u.mutation.SetSite(v)
	return _u
}

// SetNillableSite sets the "site" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableSite(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetSite(*v)
	}
	return _u
}

// ClearSite clears the value of the "site" field.
func (_u *ControlActionUpdate) ClearSite() *ControlActionUpdate {
	_u.mutation.ClearSite()
	return _u
}

// SetCommand sets the "command" field.
func (_u *ControlActionUpdate) SetCommand(v string) *ControlActionUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableCommand(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *ControlActionUpdate) ClearCommand() *ControlActionUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *ControlActionUpdate) SetRequestedBy(v string) *ControlActionUpdate {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableRequestedBy(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ControlActionUpdate) SetStatus(v controlaction.Status) *ControlActionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableStatus(v *controlaction.Status) *ControlActionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExitOk sets the "exit_ok" field.
func (_u *ControlActionUpdate) SetExitOk(v bool) *ControlActionUpdate {
	_u.mutation.SetExitOk(v)
	return _u
}

// SetNillableExitOk sets the "exit_ok" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableExitOk(v *bool) *ControlActionUpdate {
	if v != nil {
		_u.SetExitOk(*v)
	}
	return _u
}

// SetOutput sets the "output" field.
func (_u *ControlActionUpdate) SetOutput(v string) *ControlActionUpdate {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableOutput(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *ControlActionUpdate) ClearOutput() *ControlActionUpdate {
	_u.mutation.ClearOutput()
	return _u
}

// SetError sets the "error" field.
func (_u *ControlActionUpdate) SetError(v string) *ControlActionUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableError(v *string) *ControlActionUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ControlActionUpdate) ClearError() *ControlActionUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ControlActionUpdate) SetDurationMs(v int) *ControlActionUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableDurationMs(v *int) *ControlActionUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ControlActionUpdate) AddDurationMs(v int) *ControlActionUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ControlActionUpdate) SetFinishedAt(v time.Time) *ControlActionUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ControlActionUpdate) SetNillableFinishedAt(v *time.Time) *ControlActionUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ControlActionUpdate) ClearFinishedAt() *ControlActionUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *ControlActionUpdate) SetServer(v *Server) *ControlActionUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the ControlActionMutation object of the builder.
func (_u *ControlActionUpdate) Mutation() *ControlActionMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *ControlActionUpdate) ClearServer() *ControlActionUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ControlActionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ControlActionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ControlActionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ControlActionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ControlActionUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := controlaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ControlAction.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := controlaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ControlAction.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := controlaction.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "ControlAction.duration_ms": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ControlAction.server"`)
	}
	return nil
}

func (_u *ControlActionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(controlaction.Table, controlaction.Columns, sqlgraph.NewFieldSpec(controlaction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(controlaction.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.BenchPath(); ok {
		_spec.SetField(controlaction.FieldBenchPath, field.TypeString, value)
	}
	if _u.mutation.BenchPathCleared() {
		_spec.ClearField(controlaction.FieldBenchPath, field.TypeString)
	}
	if value, ok := _u.mutation.Site(); ok {
		_spec.SetField(controlaction.FieldSite, field.TypeString, value)
	}
	if _u.mutation.SiteCleared() {
		_spec.ClearField(controlaction.FieldSite, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(controlaction.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(controlaction.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(controlaction.FieldRequestedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(controlaction.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExitOk(); ok {
		_spec.SetField(controlaction.FieldExitOk, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(controlaction.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(controlaction.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(controlaction.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(controlaction.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(controlaction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(controlaction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(controlaction.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(controlaction.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   controlaction.ServerTable,
			Columns: []string{controlaction.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   controlaction.ServerTable,
			Columns: []string{controlaction.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{controlaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ControlActionUpdateOne is the builder for updating a single ControlAction entity.
type ControlActionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ControlActionMutation
}

// SetServerID sets the "server_id" field.
func (_u *ControlActionUpdateOne) SetServerID(v int) *ControlActionUpdateOne {
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableServerID(v *int) *ControlActionUpdateOne {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *ControlActionUpdateOne) SetAction(v string) *ControlActionUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableAction(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetBenchPath sets the "bench_path" field.
func (_u *ControlActionUpdateOne) SetBenchPath(v string) *ControlActionUpdateOne {
	_u.mutation.SetBenchPath(v)
	return _u
}

// SetNillableBenchPath sets the "bench_path" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableBenchPath(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetBenchPath(*v)
	}
	return _u
}

// ClearBenchPath clears the value of the "bench_path" field.
func (_u *ControlActionUpdateOne) ClearBenchPath() *ControlActionUpdateOne {
	_u.mutation.ClearBenchPath()
	return _u
}

// SetSite sets the "site" field.
func (_u *ControlActionUpdateOne) SetSite(v string) *ControlActionUpdateOne {
	_u.mutation.SetSite(v)
	return _u
}

// SetNillableSite sets the "site" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableSite(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetSite(*v)
	}
	return _u
}

// ClearSite clears the value of the "site" field.
func (_u *ControlActionUpdateOne) ClearSite() *ControlActionUpdateOne {
	_u.mutation.ClearSite()
	return _u
}

// SetCommand sets the "command" field.
func (_u *ControlActionUpdateOne) SetCommand(v string) *ControlActionUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableCommand(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *ControlActionUpdateOne) ClearCommand() *ControlActionUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *ControlActionUpdateOne) SetRequestedBy(v string) *ControlActionUpdateOne {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableRequestedBy(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ControlActionUpdateOne) SetStatus(v controlaction.Status) *ControlActionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableStatus(v *controlaction.Status) *ControlActionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExitOk sets the "exit_ok" field.
func (_u *ControlActionUpdateOne) SetExitOk(v bool) *ControlActionUpdateOne {
	_u.mutation.SetExitOk(v)
	return _u
}

// SetNillableExitOk sets the "exit_ok" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableExitOk(v *bool) *ControlActionUpdateOne {
	if v != nil {
		_u.SetExitOk(*v)
	}
	return _u
}

// SetOutput sets the "output" field.
func (_u *ControlActionUpdateOne) SetOutput(v string) *ControlActionUpdateOne {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableOutput(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *ControlActionUpdateOne) ClearOutput() *ControlActionUpdateOne {
	_u.mutation.ClearOutput()
	return _u
}

// SetError sets the "error" field.
func (_u *ControlActionUpdateOne) SetError(v string) *ControlActionUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableError(v *string) *ControlActionUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ControlActionUpdateOne) ClearError() *ControlActionUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ControlActionUpdateOne) SetDurationMs(v int) *ControlActionUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableDurationMs(v *int) *ControlActionUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ControlActionUpdateOne) AddDurationMs(v int) *ControlActionUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ControlActionUpdateOne) SetFinishedAt(v time.Time) *ControlActionUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ControlActionUpdateOne) SetNillableFinishedAt(v *time.Time) *ControlActionUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ControlActionUpdateOne) ClearFinishedAt() *ControlActionUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *ControlActionUpdateOne) SetServer(v *Server) *ControlActionUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the ControlActionMutation object of the builder.
func (_u *ControlActionUpdateOne) Mutation() *ControlActionMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *ControlActionUpdateOne) ClearServer() *ControlActionUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the ControlActionUpdate builder.
func (_u *ControlActionUpdateOne) Where(ps ...predicate.ControlAction) *ControlActionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ControlActionUpdateOne) Select(field string, fields ...string) *ControlActionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ControlAction entity.
func (_u *ControlActionUpdateOne) Save(ctx context.Context) (*ControlAction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ControlActionUpdateOne) SaveX(ctx context.Context) *ControlAction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ControlActionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ControlActionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ControlActionUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := controlaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ControlAction.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := controlaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ControlAction.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := controlaction.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "ControlAction.duration_ms": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ControlAction.server"`)
	}
	return nil
}

func (_u *ControlActionUpdateOne) sqlSave(ctx context.Context) (_node *ControlAction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(controlaction.Table, controlaction.Columns, sqlgraph.NewFieldSpec(controlaction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ControlAction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, controlaction.FieldID)
		for _, f := range fields {
			if !controlaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != controlaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(controlaction.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.BenchPath(); ok {
		_spec.SetField(controlaction.FieldBenchPath, field.TypeString, value)
	}
	if _u.mutation.BenchPathCleared() {
		_spec.ClearField(controlaction.FieldBenchPath, field.TypeString)
	}
	if value, ok := _u.mutation.Site(); ok {
		_spec.SetField(controlaction.FieldSite, field.TypeString, value)
	}
	if _u.mutation.SiteCleared() {
		_spec.ClearField(controlaction.FieldSite, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(controlaction.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(controlaction.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(controlaction.FieldRequestedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(controlaction.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExitOk(); ok {
		_spec.SetField(controlaction.FieldExitOk, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(controlaction.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(controlaction.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(controlaction.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(controlaction.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(controlaction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(controlaction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(controlaction.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(controlaction.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   controlaction.ServerTable,
			Columns: []string{controlaction.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   controlaction.ServerTable,
			Columns: []string{controlaction.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ControlAction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{controlaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
