// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"frappe-monitor/ent/controlaction"
	"frappe-monitor/ent/server"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ControlAction is the model entity for the ControlAction schema.
type ControlAction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ServerID holds the value of the "server_id" field.
	ServerID int `json:"server_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// BenchPath holds the value of the "bench_path" field.
	BenchPath string `json:"bench_path,omitempty"`
	// Site holds the value of the "site" field.
	Site string `json:"site,omitempty"`
	// Command holds the value of the "command" field.
	Command string `json:"command,omitempty"`
	// RequestedBy holds the value of the "requested_by" field.
	RequestedBy string `json:"requested_by,omitempty"`
	// Status holds the value of the "status" field.
	Status controlaction.Status `json:"status,omitempty"`
	// ExitOk holds the value of the "exit_ok" field.
	ExitOk bool `json:"exit_ok,omitempty"`
	// Output holds the value of the "output" field.
	Output string `json:"output,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int `json:"duration_ms,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ControlActionQuery when eager-loading is set.
	Edges        ControlActionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ControlActionEdges holds the relations/edges for other nodes in the graph.
type ControlActionEdges struct {
	// Server holds the value of the server edge.
	Server *Server `json:"server,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServerOrErr returns the Server value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ControlActionEdges) ServerOrErr() (*Server, error) {
	if e.Server != nil {
		return e.Server, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: server.Label}
	}
	return nil, &NotLoadedError{edge: "server"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ControlAction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case controlaction.FieldExitOk:
			values[i] = new(sql.NullBool)
		case controlaction.FieldID, controlaction.FieldServerID, controlaction.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case controlaction.FieldAction, controlaction.FieldBenchPath, controlaction.FieldSite, controlaction.FieldCommand, controlaction.FieldRequestedBy, controlaction.FieldStatus, controlaction.FieldOutput, controlaction.FieldError:
			values[i] = new(sql.NullString)
		case controlaction.FieldCreatedAt, controlaction.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ControlAction fields.
func (_m *ControlAction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case controlaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case controlaction.FieldServerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field server_id", values[i])
			} else if value.Valid {
				_m.ServerID = int(value.Int64)
			}
		case controlaction.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case controlaction.FieldBenchPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bench_path", values[i])
			} else if value.Valid {
				_m.BenchPath = value.String
			}
		case controlaction.FieldSite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site", values[i])
			} else if value.Valid {
				_m.Site = value.String
			}
		case controlaction.FieldCommand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field command", values[i])
			} else if value.Valid {
				_m.Command = value.String
			}
		case controlaction.FieldRequestedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_by", values[i])
			} else if value.Valid {
				_m.RequestedBy = value.String
			}
		case controlaction.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = controlaction.Status(value.String)
			}
		case controlaction.FieldExitOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field exit_ok", values[i])
			} else if value.Valid {
				_m.ExitOk = value.Bool
			}
		case controlaction.FieldOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output", values[i])
			} else if value.Valid {
				_m.Output = value.String
			}
		case controlaction.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case controlaction.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = int(value.Int64)
			}
		case controlaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case controlaction.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ControlAction.
// This includes values selected through modifiers, order, etc.
func (_m *ControlAction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryServer queries the "server" edge of the ControlAction entity.
func (_m *ControlAction) QueryServer() *ServerQuery {
	return NewControlActionClient(_m.config).QueryServer(_m)
}

// Update returns a builder for updating this ControlAction.
// Note that you need to call ControlAction.Unwrap() before calling this method if this ControlAction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ControlAction) Update() *ControlActionUpdateOne {
	return NewControlActionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ControlAction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ControlAction) Unwrap() *ControlAction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ControlAction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ControlAction) String() string {
	var builder strings.Builder
	builder.WriteString("ControlAction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("server_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServerID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("bench_path=")
	builder.WriteString(_m.BenchPath)
	builder.WriteString(", ")
	builder.WriteString("site=")
	builder.WriteString(_m.Site)
	builder.WriteString(", ")
	builder.WriteString("command=")
	builder.WriteString(_m.Command)
	builder.WriteString(", ")
	builder.WriteString("requested_by=")
	builder.WriteString(_m.RequestedBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("exit_ok=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExitOk))
	builder.WriteString(", ")
	builder.WriteString("output=")
	builder.WriteString(_m.Output)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ControlActions is a parsable slice of ControlAction.
type ControlActions []*ControlAction
