// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/dbtarget"
	"frappe-monitor/ent/server"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DBTargetCreate is the builder for creating a DBTarget entity.
type DBTargetCreate struct {
	config
	mutation *DBTargetMutation
	hooks    []Hook
}

// SetServerID sets the "server_id" field.
func (_c *DBTargetCreate) SetServerID(v int) *DBTargetCreate {
	_c.mutation.SetServerID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DBTargetCreate) SetName(v string) *DBTargetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DBTargetCreate) SetEnabled(v bool) *DBTargetCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableEnabled(v *bool) *DBTargetCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLagThresholdSeconds sets the "lag_threshold_seconds" field.
func (_c *DBTargetCreate) SetLagThresholdSeconds(v int) *DBTargetCreate {
	_c.mutation.SetLagThresholdSeconds(v)
	return _c
}

// SetNillableLagThresholdSeconds sets the "lag_threshold_seconds" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableLagThresholdSeconds(v *int) *DBTargetCreate {
	if v != nil {
		_c.SetLagThresholdSeconds(*v)
	}
	return _c
}

// SetMysqlCommand sets the "mysql_command" field.
func (_c *DBTargetCreate) SetMysqlCommand(v string) *DBTargetCreate {
	_c.mutation.SetMysqlCommand(v)
	return _c
}

// SetNillableMysqlCommand sets the "mysql_command" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableMysqlCommand(v *string) *DBTargetCreate {
	if v != nil {
		_c.SetMysqlCommand(*v)
	}
	return _c
}

// SetDefaultsFile sets the "defaults_file" field.
func (_c *DBTargetCreate) SetDefaultsFile(v string) *DBTargetCreate {
	_c.mutation.SetDefaultsFile(v)
	return _c
}

// SetNillableDefaultsFile sets the "defaults_file" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableDefaultsFile(v *string) *DBTargetCreate {
	if v != nil {
		_c.SetDefaultsFile(*v)
	}
	return _c
}

// SetSocket sets the "socket" field.
func (_c *DBTargetCreate) SetSocket(v string) *DBTargetCreate {
	_c.mutation.SetSocket(v)
	return _c
}

// SetNillableSocket sets the "socket" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableSocket(v *string) *DBTargetCreate {
	if v != nil {
		_c.SetSocket(*v)
	}
	return _c
}

// SetHeartbeatEnabled sets the "heartbeat_enabled" field.
func (_c *DBTargetCreate) SetHeartbeatEnabled(v bool) *DBTargetCreate {
	_c.mutation.SetHeartbeatEnabled(v)
	return _c
}

// SetNillableHeartbeatEnabled sets the "heartbeat_enabled" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableHeartbeatEnabled(v *bool) *DBTargetCreate {
	if v != nil {
		_c.SetHeartbeatEnabled(*v)
	}
	return _c
}

// SetHeartbeatQuery sets the "heartbeat_query" field.
func (_c *DBTargetCreate) SetHeartbeatQuery(v string) *DBTargetCreate {
	_c.mutation.SetHeartbeatQuery(v)
	return _c
}

// SetNillableHeartbeatQuery sets the "heartbeat_query" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableHeartbeatQuery(v *string) *DBTargetCreate {
	if v != nil {
		_c.SetHeartbeatQuery(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DBTargetCreate) SetStatus(v dbtarget.Status) *DBTargetCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableStatus(v *dbtarget.Status) *DBTargetCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *DBTargetCreate) SetLastCheckedAt(v time.Time) *DBTargetCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableLastCheckedAt(v *time.Time) *DBTargetCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetLagSeconds sets the "lag_seconds" field.
func (_c *DBTargetCreate) SetLagSeconds(v int64) *DBTargetCreate {
	_c.mutation.SetLagSeconds(v)
	return _c
}

// SetNillableLagSeconds sets the "lag_seconds" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableLagSeconds(v *int64) *DBTargetCreate {
	if v != nil {
		_c.SetLagSeconds(*v)
	}
	return _c
}

// SetHeartbeatLagSeconds sets the "heartbeat_lag_seconds" field.
func (_c *DBTargetCreate) SetHeartbeatLagSeconds(v float64) *DBTargetCreate {
	_c.mutation.SetHeartbeatLagSeconds(v)
	return _c
}

// SetNillableHeartbeatLagSeconds sets the "heartbeat_lag_seconds" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableHeartbeatLagSeconds(v *float64) *DBTargetCreate {
	if v != nil {
		_c.SetHeartbeatLagSeconds(*v)
	}
	return _c
}

// SetIoRunning sets the "io_running" field.
func (_c *DBTargetCreate) SetIoRunning(v bool) *DBTargetCreate {
	_c.mutation.SetIoRunning(v)
	return _c
}

// SetNillableIoRunning sets the "io_running" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableIoRunning(v *bool) *DBTargetCreate {
	if v != nil {
		_c.SetIoRunning(*v)
	}
	return _c
}

// SetSQLRunning sets the "sql_running" field.
func (_c *DBTargetCreate) SetSQLRunning(v bool) *DBTargetCreate {
	_c.mutation.SetSQLRunning(v)
	return _c
}

// SetNillableSQLRunning sets the "sql_running" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableSQLRunning(v *bool) *DBTargetCreate {
	if v != nil {
		_c.SetSQLRunning(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *DBTargetCreate) SetLastError(v string) *DBTargetCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableLastError(v *string) *DBTargetCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DBTargetCreate) SetCreatedAt(v time.Time) *DBTargetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableCreatedAt(v *time.Time) *DBTargetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DBTargetCreate) SetUpdatedAt(v time.Time) *DBTargetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DBTargetCreate) SetNillableUpdatedAt(v *time.Time) *DBTargetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetServer sets the "server" edge to the Server entity.
func (_c *DBTargetCreate) SetServer(v *Server) *DBTargetCreate {
	return _c.SetServerID(v.ID)
}

// Mutation returns the DBTargetMutation object of the builder.
func (_c *DBTargetCreate) Mutation() *DBTargetMutation {
	return _c.mutation
}

// Save creates the DBTarget in the database.
func (_c *DBTargetCreate) Save(ctx context.Context) (*DBTarget, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DBTargetCreate) SaveX(ctx context.Context) *DBTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DBTargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DBTargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DBTargetCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := dbtarget.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.LagThresholdSeconds(); !ok {
		v := dbtarget.DefaultLagThresholdSeconds
		_c.mutation.SetLagThresholdSeconds(v)
	}
	if _, ok := _c.mutation.MysqlCommand(); !ok {
		v := dbtarget.DefaultMysqlCommand
		_c.mutation.SetMysqlCommand(v)
	}
	if _, ok := _c.mutation.HeartbeatEnabled(); !ok {
		v := dbtarget.DefaultHeartbeatEnabled
		_c.mutation.SetHeartbeatEnabled(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := dbtarget.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IoRunning(); !ok {
		v := dbtarget.DefaultIoRunning
		_c.mutation.SetIoRunning(v)
	}
	if _, ok := _c.mutation.SQLRunning(); !ok {
		v := dbtarget.DefaultSQLRunning
		_c.mutation.SetSQLRunning(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dbtarget.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dbtarget.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DBTargetCreate) check() error {
	if _, ok := _c.mutation.ServerID(); !ok {
		return &ValidationError{Name: "server_id", err: errors.New(`ent: missing required field "DBTarget.server_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DBTarget.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := dbtarget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DBTarget.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "DBTarget.enabled"`)}
	}
	if _, ok := _c.mutation.LagThresholdSeconds(); !ok {
		return &ValidationError{Name: "lag_threshold_seconds", err: errors.New(`ent: missing required field "DBTarget.lag_threshold_seconds"`)}
	}
	if v, ok := _c.mutation.LagThresholdSeconds(); ok {
		if err := dbtarget.LagThresholdSecondsValidator(v); err != nil {
			return &ValidationError{Name: "lag_threshold_seconds", err: fmt.Errorf(`ent: validator failed for field "DBTarget.lag_threshold_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MysqlCommand(); !ok {
		return &ValidationError{Name: "mysql_command", err: errors.New(`ent: missing required field "DBTarget.mysql_command"`)}
	}
	if _, ok := _c.mutation.HeartbeatEnabled(); !ok {
		return &ValidationError{Name: "heartbeat_enabled", err: errors.New(`ent: missing required field "DBTarget.heartbeat_enabled"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DBTarget.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := dbtarget.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DBTarget.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IoRunning(); !ok {
		return &ValidationError{Name: "io_running", err: errors.New(`ent: missing required field "DBTarget.io_running"`)}
	}
	if _, ok := _c.mutation.SQLRunning(); !ok {
		return &ValidationError{Name: "sql_running", err: errors.New(`ent: missing required field "DBTarget.sql_running"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DBTarget.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DBTarget.updated_at"`)}
	}
	if len(_c.mutation.ServerIDs()) == 0 {
		return &ValidationError{Name: "server", err: errors.New(`ent: missing required edge "DBTarget.server"`)}
	}
	return nil
}

func (_c *DBTargetCreate) sqlSave(ctx context.Context) (*DBTarget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DBTargetCreate) createSpec() (*DBTarget, *sqlgraph.CreateSpec) {
	var (
		_node = &DBTarget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dbtarget.Table, sqlgraph.NewFieldSpec(dbtarget.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dbtarget.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(dbtarget.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LagThresholdSeconds(); ok {
		_spec.SetField(dbtarget.FieldLagThresholdSeconds, field.TypeInt, value)
		_node.LagThresholdSeconds = value
	}
	if value, ok := _c.mutation.MysqlCommand(); ok {
		_spec.SetField(dbtarget.FieldMysqlCommand, field.TypeString, value)
		_node.MysqlCommand = value
	}
	if value, ok := _c.mutation.DefaultsFile(); ok {
		_spec.SetField(dbtarget.FieldDefaultsFile, field.TypeString, value)
		_node.DefaultsFile = value
	}
	if value, ok := _c.mutation.Socket(); ok {
		_spec.SetField(dbtarget.FieldSocket, field.TypeString, value)
		_node.Socket = value
	}
	if value, ok := _c.mutation.HeartbeatEnabled(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatEnabled, field.TypeBool, value)
		_node.HeartbeatEnabled = value
	}
	if value, ok := _c.mutation.HeartbeatQuery(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatQuery, field.TypeString, value)
		_node.HeartbeatQuery = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(dbtarget.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(dbtarget.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.LagSeconds(); ok {
		_spec.SetField(dbtarget.FieldLagSeconds, field.TypeInt64, value)
		_node.LagSeconds = &value
	}
	if value, ok := _c.mutation.HeartbeatLagSeconds(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64, value)
		_node.HeartbeatLagSeconds = &value
	}
	if value, ok := _c.mutation.IoRunning(); ok {
		_spec.SetField(dbtarget.FieldIoRunning, field.TypeBool, value)
		_node.IoRunning = value
	}
	if value, ok := _c.mutation.SQLRunning(); ok {
		_spec.SetField(dbtarget.FieldSQLRunning, field.TypeBool, value)
		_node.SQLRunning = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(dbtarget.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dbtarget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dbtarget.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dbtarget.ServerTable,
			Columns: []string{dbtarget.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DBTargetCreateBulk is the builder for creating many DBTarget entities in bulk.
type DBTargetCreateBulk struct {
	config
	err      error
	builders []*DBTargetCreate
}

// Save creates the DBTarget entities in the database.
func (_c *DBTargetCreateBulk) Save(ctx context.Context) ([]*DBTarget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DBTarget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DBTargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DBTargetCreateBulk) SaveX(ctx context.Context) []*DBTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DBTargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DBTargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
