// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/dbtarget"
	"frappe-monitor/ent/predicate"
	"frappe-monitor/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DBTargetUpdate is the builder for updating DBTarget entities.
type DBTargetUpdate struct {
	config
	hooks    []Hook
	mutation *DBTargetMutation
}

// Where appends a list predicates to the DBTargetUpdate builder.
func (_u *DBTargetUpdate) Where(ps ...predicate.DBTarget) *DBTargetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServerID sets the "server_id" field.
func (_u *DBTargetUpdate) SetServerID(v int) *DBTargetUpdate {
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableServerID(v *int) *DBTargetUpdate {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DBTargetUpdate) SetName(v string) *DBTargetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableName(v *string) *DBTargetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DBTargetUpdate) SetEnabled(v bool) *DBTargetUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableEnabled(v *bool) *DBTargetUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLagThresholdSeconds sets the "lag_threshold_seconds" field.
func (_u *DBTargetUpdate) SetLagThresholdSeconds(v int) *DBTargetUpdate {
	_u.mutation.ResetLagThresholdSeconds()
	_u.mutation.SetLagThresholdSeconds(v)
	return _u
}

// SetNillableLagThresholdSeconds sets the "lag_threshold_seconds" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableLagThresholdSeconds(v *int) *DBTargetUpdate {
	if v != nil {
		_u.SetLagThresholdSeconds(*v)
	}
	return _u
}

// AddLagThresholdSeconds adds value to the "lag_threshold_seconds" field.
func (_u *DBTargetUpdate) AddLagThresholdSeconds(v int) *DBTargetUpdate {
	_u.mutation.AddLagThresholdSeconds(v)
	return _u
}

// SetMysqlCommand sets the "mysql_command" field.
func (_u *DBTargetUpdate) SetMysqlCommand(v string) *DBTargetUpdate {
	_u.mutation.SetMysqlCommand(v)
	return _u
}

// SetNillableMysqlCommand sets the "mysql_command" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableMysqlCommand(v *string) *DBTargetUpdate {
	if v != nil {
		_u.SetMysqlCommand(*v)
	}
	return _u
}

// SetDefaultsFile sets the "defaults_file" field.
func (_u *DBTargetUpdate) SetDefaultsFile(v string) *DBTargetUpdate {
	_u.mutation.SetDefaultsFile(v)
	return _u
}

// SetNillableDefaultsFile sets the "defaults_file" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableDefaultsFile(v *string) *DBTargetUpdate {
	if v != nil {
		_u.SetDefaultsFile(*v)
	}
	return _u
}

// ClearDefaultsFile clears the value of the "defaults_file" field.
func (_u *DBTargetUpdate) ClearDefaultsFile() *DBTargetUpdate {
	_u.mutation.ClearDefaultsFile()
	return _u
}

// SetSocket sets the "socket" field.
func (_u *DBTargetUpdate) SetSocket(v string) *DBTargetUpdate {
	_u.mutation.SetSocket(v)
	return _u
}

// SetNillableSocket sets the "socket" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableSocket(v *string) *DBTargetUpdate {
	if v != nil {
		_u.SetSocket(*v)
	}
	return _u
}

// ClearSocket clears the value of the "socket" field.
func (_u *DBTargetUpdate) ClearSocket() *DBTargetUpdate {
	_u.mutation.ClearSocket()
	return _u
}

// SetHeartbeatEnabled sets the "heartbeat_enabled" field.
func (_u *DBTargetUpdate) SetHeartbeatEnabled(v bool) *DBTargetUpdate {
	_u.mutation.SetHeartbeatEnabled(v)
	return _u
}

// SetNillableHeartbeatEnabled sets the "heartbeat_enabled" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableHeartbeatEnabled(v *bool) *DBTargetUpdate {
	if v != nil {
		_u.SetHeartbeatEnabled(*v)
	}
	return _u
}

// SetHeartbeatQuery sets the "heartbeat_query" field.
func (_u *DBTargetUpdate) SetHeartbeatQuery(v string) *DBTargetUpdate {
	_u.mutation.SetHeartbeatQuery(v)
	return _u
}

// SetNillableHeartbeatQuery sets the "heartbeat_query" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableHeartbeatQuery(v *string) *DBTargetUpdate {
	if v != nil {
		_u.SetHeartbeatQuery(*v)
	}
	return _u
}

// ClearHeartbeatQuery clears the value of the "heartbeat_query" field.
func (_u *DBTargetUpdate) ClearHeartbeatQuery() *DBTargetUpdate {
	_u.mutation.ClearHeartbeatQuery()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DBTargetUpdate) SetStatus(v dbtarget.Status) *DBTargetUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableStatus(v *dbtarget.Status) *DBTargetUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *DBTargetUpdate) SetLastCheckedAt(v time.Time) *DBTargetUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableLastCheckedAt(v *time.Time) *DBTargetUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *DBTargetUpdate) ClearLastCheckedAt() *DBTargetUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLagSeconds sets the "lag_seconds" field.
func (_u *DBTargetUpdate) SetLagSeconds(v int64) *DBTargetUpdate {
	_u.mutation.ResetLagSeconds()
	_u.mutation.SetLagSeconds(v)
	return _u
}

// SetNillableLagSeconds sets the "lag_seconds" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableLagSeconds(v *int64) *DBTargetUpdate {
	if v != nil {
		_u.SetLagSeconds(*v)
	}
	return _u
}

// AddLagSeconds adds value to the "lag_seconds" field.
func (_u *DBTargetUpdate) AddLagSeconds(v int64) *DBTargetUpdate {
	_u.mutation.AddLagSeconds(v)
	return _u
}

// ClearLagSeconds clears the value of the "lag_seconds" field.
func (_u *DBTargetUpdate) ClearLagSeconds() *DBTargetUpdate {
	_u.mutation.ClearLagSeconds()
	return _u
}

// SetHeartbeatLagSeconds sets the "heartbeat_lag_seconds" field.
func (_u *DBTargetUpdate) SetHeartbeatLagSeconds(v float64) *DBTargetUpdate {
	_u.mutation.ResetHeartbeatLagSeconds()
	_u.mutation.SetHeartbeatLagSeconds(v)
	return _u
}

// SetNillableHeartbeatLagSeconds sets the "heartbeat_lag_seconds" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableHeartbeatLagSeconds(v *float64) *DBTargetUpdate {
	if v != nil {
		_u.SetHeartbeatLagSeconds(*v)
	}
	return _u
}

// AddHeartbeatLagSeconds adds value to the "heartbeat_lag_seconds" field.
func (_u *DBTargetUpdate) AddHeartbeatLagSeconds(v float64) *DBTargetUpdate {
	_u.mutation.AddHeartbeatLagSeconds(v)
	return _u
}

// ClearHeartbeatLagSeconds clears the value of the "heartbeat_lag_seconds" field.
func (_u *DBTargetUpdate) ClearHeartbeatLagSeconds() *DBTargetUpdate {
	_u.mutation.ClearHeartbeatLagSeconds()
	return _u
}

// SetIoRunning sets the "io_running" field.
func (_u *DBTargetUpdate) SetIoRunning(v bool) *DBTargetUpdate {
	_u.mutation.SetIoRunning(v)
	return _u
}

// SetNillableIoRunning sets the "io_running" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableIoRunning(v *bool) *DBTargetUpdate {
	if v != nil {
		_u.SetIoRunning(*v)
	}
	return _u
}

// SetSQLRunning sets the "sql_running" field.
func (_u *DBTargetUpdate) SetSQLRunning(v bool) *DBTargetUpdate {
	_u.mutation.SetSQLRunning(v)
	return _u
}

// SetNillableSQLRunning sets the "sql_running" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableSQLRunning(v *bool) *DBTargetUpdate {
	if v != nil {
		_u.SetSQLRunning(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *DBTargetUpdate) SetLastError(v string) *DBTargetUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *DBTargetUpdate) SetNillableLastError(v *string) *DBTargetUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *DBTargetUpdate) ClearLastError() *DBTargetUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DBTargetUpdate) SetUpdatedAt(v time.Time) *DBTargetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *DBTargetUpdate) SetServer(v *Server) *DBTargetUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the DBTargetMutation object of the builder.
func (_u *DBTargetUpdate) Mutation() *DBTargetMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *DBTargetUpdate) ClearServer() *DBTargetUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DBTargetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DBTargetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DBTargetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DBTargetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DBTargetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dbtarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DBTargetUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dbtarget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DBTarget.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LagThresholdSeconds(); ok {
		if err := dbtarget.LagThresholdSecondsValidator(v); err != nil {
			return &ValidationError{Name: "lag_threshold_seconds", err: fmt.Errorf(`ent: validator failed for field "DBTarget.lag_threshold_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := dbtarget.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DBTarget.status": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DBTarget.server"`)
	}
	return nil
}

func (_u *DBTargetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dbtarget.Table, dbtarget.Columns, sqlgraph.NewFieldSpec(dbtarget.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dbtarget.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dbtarget.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LagThresholdSeconds(); ok {
		_spec.SetField(dbtarget.FieldLagThresholdSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLagThresholdSeconds(); ok {
		_spec.AddField(dbtarget.FieldLagThresholdSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MysqlCommand(); ok {
		_spec.SetField(dbtarget.FieldMysqlCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultsFile(); ok {
		_spec.SetField(dbtarget.FieldDefaultsFile, field.TypeString, value)
	}
	if _u.mutation.DefaultsFileCleared() {
		_spec.ClearField(dbtarget.FieldDefaultsFile, field.TypeString)
	}
	if value, ok := _u.mutation.Socket(); ok {
		_spec.SetField(dbtarget.FieldSocket, field.TypeString, value)
	}
	if _u.mutation.SocketCleared() {
		_spec.ClearField(dbtarget.FieldSocket, field.TypeString)
	}
	if value, ok := _u.mutation.HeartbeatEnabled(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HeartbeatQuery(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatQuery, field.TypeString, value)
	}
	if _u.mutation.HeartbeatQueryCleared() {
		_spec.ClearField(dbtarget.FieldHeartbeatQuery, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dbtarget.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(dbtarget.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(dbtarget.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LagSeconds(); ok {
		_spec.SetField(dbtarget.FieldLagSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLagSeconds(); ok {
		_spec.AddField(dbtarget.FieldLagSeconds, field.TypeInt64, value)
	}
	if _u.mutation.LagSecondsCleared() {
		_spec.ClearField(dbtarget.FieldLagSeconds, field.TypeInt64)
	}
	if value, ok := _u.mutation.HeartbeatLagSeconds(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeartbeatLagSeconds(); ok {
		_spec.AddField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64, value)
	}
	if _u.mutation.HeartbeatLagSecondsCleared() {
		_spec.ClearField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IoRunning(); ok {
		_spec.SetField(dbtarget.FieldIoRunning, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SQLRunning(); ok {
		_spec.SetField(dbtarget.FieldSQLRunning, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(dbtarget.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(dbtarget.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dbtarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dbtarget.ServerTable,
			Columns: []string{dbtarget.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dbtarget.ServerTable,
			Columns: []string{dbtarget.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dbtarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DBTargetUpdateOne is the builder for updating a single DBTarget entity.
type DBTargetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DBTargetMutation
}

// SetServerID sets the "server_id" field.
func (_u *DBTargetUpdateOne) SetServerID(v int) *DBTargetUpdateOne {
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableServerID(v *int) *DBTargetUpdateOne {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DBTargetUpdateOne) SetName(v string) *DBTargetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableName(v *string) *DBTargetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DBTargetUpdateOne) SetEnabled(v bool) *DBTargetUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableEnabled(v *bool) *DBTargetUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLagThresholdSeconds sets the "lag_threshold_seconds" field.
func (_u *DBTargetUpdateOne) SetLagThresholdSeconds(v int) *DBTargetUpdateOne {
	_u.mutation.ResetLagThresholdSeconds()
	_u.mutation.SetLagThresholdSeconds(v)
	return _u
}

// SetNillableLagThresholdSeconds sets the "lag_threshold_seconds" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableLagThresholdSeconds(v *int) *DBTargetUpdateOne {
	if v != nil {
		_u.SetLagThresholdSeconds(*v)
	}
	return _u
}

// AddLagThresholdSeconds adds value to the "lag_threshold_seconds" field.
func (_u *DBTargetUpdateOne) AddLagThresholdSeconds(v int) *DBTargetUpdateOne {
	_u.mutation.AddLagThresholdSeconds(v)
	return _u
}

// SetMysqlCommand sets the "mysql_command" field.
func (_u *DBTargetUpdateOne) SetMysqlCommand(v string) *DBTargetUpdateOne {
	_u.mutation.SetMysqlCommand(v)
	return _u
}

// SetNillableMysqlCommand sets the "mysql_command" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableMysqlCommand(v *string) *DBTargetUpdateOne {
	if v != nil {
		_u.SetMysqlCommand(*v)
	}
	return _u
}

// SetDefaultsFile sets the "defaults_file" field.
func (_u *DBTargetUpdateOne) SetDefaultsFile(v string) *DBTargetUpdateOne {
	_u.mutation.SetDefaultsFile(v)
	return _u
}

// SetNillableDefaultsFile sets the "defaults_file" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableDefaultsFile(v *string) *DBTargetUpdateOne {
	if v != nil {
		_u.SetDefaultsFile(*v)
	}
	return _u
}

// ClearDefaultsFile clears the value of the "defaults_file" field.
func (_u *DBTargetUpdateOne) ClearDefaultsFile() *DBTargetUpdateOne {
	_u.mutation.ClearDefaultsFile()
	return _u
}

// SetSocket sets the "socket" field.
func (_u *DBTargetUpdateOne) SetSocket(v string) *DBTargetUpdateOne {
	_u.mutation.SetSocket(v)
	return _u
}

// SetNillableSocket sets the "socket" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableSocket(v *string) *DBTargetUpdateOne {
	if v != nil {
		_u.SetSocket(*v)
	}
	return _u
}

// ClearSocket clears the value of the "socket" field.
func (_u *DBTargetUpdateOne) ClearSocket() *DBTargetUpdateOne {
	_u.mutation.ClearSocket()
	return _u
}

// SetHeartbeatEnabled sets the "heartbeat_enabled" field.
func (_u *DBTargetUpdateOne) SetHeartbeatEnabled(v bool) *DBTargetUpdateOne {
	_u.mutation.SetHeartbeatEnabled(v)
	return _u
}

// SetNillableHeartbeatEnabled sets the "heartbeat_enabled" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableHeartbeatEnabled(v *bool) *DBTargetUpdateOne {
	if v != nil {
		_u.SetHeartbeatEnabled(*v)
	}
	return _u
}

// SetHeartbeatQuery sets the "heartbeat_query" field.
func (_u *DBTargetUpdateOne) SetHeartbeatQuery(v string) *DBTargetUpdateOne {
	_u.mutation.SetHeartbeatQuery(v)
	return _u
}

// SetNillableHeartbeatQuery sets the "heartbeat_query" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableHeartbeatQuery(v *string) *DBTargetUpdateOne {
	if v != nil {
		_u.SetHeartbeatQuery(*v)
	}
	return _u
}

// ClearHeartbeatQuery clears the value of the "heartbeat_query" field.
func (_u *DBTargetUpdateOne) ClearHeartbeatQuery() *DBTargetUpdateOne {
	_u.mutation.ClearHeartbeatQuery()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DBTargetUpdateOne) SetStatus(v dbtarget.Status) *DBTargetUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableStatus(v *dbtarget.Status) *DBTargetUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *DBTargetUpdateOne) SetLastCheckedAt(v time.Time) *DBTargetUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableLastCheckedAt(v *time.Time) *DBTargetUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *DBTargetUpdateOne) ClearLastCheckedAt() *DBTargetUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLagSeconds sets the "lag_seconds" field.
func (_u *DBTargetUpdateOne) SetLagSeconds(v int64) *DBTargetUpdateOne {
	_u.mutation.ResetLagSeconds()
	_u.mutation.SetLagSeconds(v)
	return _u
}

// SetNillableLagSeconds sets the "lag_seconds" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableLagSeconds(v *int64) *DBTargetUpdateOne {
	if v != nil {
		_u.SetLagSeconds(*v)
	}
	return _u
}

// AddLagSeconds adds value to the "lag_seconds" field.
func (_u *DBTargetUpdateOne) AddLagSeconds(v int64) *DBTargetUpdateOne {
	_u.mutation.AddLagSeconds(v)
	return _u
}

// ClearLagSeconds clears the value of the "lag_seconds" field.
func (_u *DBTargetUpdateOne) ClearLagSeconds() *DBTargetUpdateOne {
	_u.mutation.ClearLagSeconds()
	return _u
}

// SetHeartbeatLagSeconds sets the "heartbeat_lag_seconds" field.
func (_u *DBTargetUpdateOne) SetHeartbeatLagSeconds(v float64) *DBTargetUpdateOne {
	_u.mutation.ResetHeartbeatLagSeconds()
	_u.mutation.SetHeartbeatLagSeconds(v)
	return _u
}

// SetNillableHeartbeatLagSeconds sets the "heartbeat_lag_seconds" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableHeartbeatLagSeconds(v *float64) *DBTargetUpdateOne {
	if v != nil {
		_u.SetHeartbeatLagSeconds(*v)
	}
	return _u
}

// AddHeartbeatLagSeconds adds value to the "heartbeat_lag_seconds" field.
func (_u *DBTargetUpdateOne) AddHeartbeatLagSeconds(v float64) *DBTargetUpdateOne {
	_u.mutation.AddHeartbeatLagSeconds(v)
	return _u
}

// ClearHeartbeatLagSeconds clears the value of the "heartbeat_lag_seconds" field.
func (_u *DBTargetUpdateOne) ClearHeartbeatLagSeconds() *DBTargetUpdateOne {
	_u.mutation.ClearHeartbeatLagSeconds()
	return _u
}

// SetIoRunning sets the "io_running" field.
func (_u *DBTargetUpdateOne) SetIoRunning(v bool) *DBTargetUpdateOne {
	_u.mutation.SetIoRunning(v)
	return _u
}

// SetNillableIoRunning sets the "io_running" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableIoRunning(v *bool) *DBTargetUpdateOne {
	if v != nil {
		_u.SetIoRunning(*v)
	}
	return _u
}

// SetSQLRunning sets the "sql_running" field.
func (_u *DBTargetUpdateOne) SetSQLRunning(v bool) *DBTargetUpdateOne {
	_u.mutation.SetSQLRunning(v)
	return _u
}

// SetNillableSQLRunning sets the "sql_running" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableSQLRunning(v *bool) *DBTargetUpdateOne {
	if v != nil {
		_u.SetSQLRunning(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *DBTargetUpdateOne) SetLastError(v string) *DBTargetUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *DBTargetUpdateOne) SetNillableLastError(v *string) *DBTargetUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *DBTargetUpdateOne) ClearLastError() *DBTargetUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DBTargetUpdateOne) SetUpdatedAt(v time.Time) *DBTargetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *DBTargetUpdateOne) SetServer(v *Server) *DBTargetUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the DBTargetMutation object of the builder.
func (_u *DBTargetUpdateOne) Mutation() *DBTargetMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *DBTargetUpdateOne) ClearServer() *DBTargetUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the DBTargetUpdate builder.
func (_u *DBTargetUpdateOne) Where(ps ...predicate.DBTarget) *DBTargetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DBTargetUpdateOne) Select(field string, fields ...string) *DBTargetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DBTarget entity.
func (_u *DBTargetUpdateOne) Save(ctx context.Context) (*DBTarget, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DBTargetUpdateOne) SaveX(ctx context.Context) *DBTarget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DBTargetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DBTargetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DBTargetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dbtarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DBTargetUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dbtarget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DBTarget.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LagThresholdSeconds(); ok {
		if err := dbtarget.LagThresholdSecondsValidator(v); err != nil {
			return &ValidationError{Name: "lag_threshold_seconds", err: fmt.Errorf(`ent: validator failed for field "DBTarget.lag_threshold_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := dbtarget.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DBTarget.status": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DBTarget.server"`)
	}
	return nil
}

func (_u *DBTargetUpdateOne) sqlSave(ctx context.Context) (_node *DBTarget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dbtarget.Table, dbtarget.Columns, sqlgraph.NewFieldSpec(dbtarget.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DBTarget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dbtarget.FieldID)
		for _, f := range fields {
			if !dbtarget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dbtarget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dbtarget.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dbtarget.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LagThresholdSeconds(); ok {
		_spec.SetField(dbtarget.FieldLagThresholdSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLagThresholdSeconds(); ok {
		_spec.AddField(dbtarget.FieldLagThresholdSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MysqlCommand(); ok {
		_spec.SetField(dbtarget.FieldMysqlCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultsFile(); ok {
		_spec.SetField(dbtarget.FieldDefaultsFile, field.TypeString, value)
	}
	if _u.mutation.DefaultsFileCleared() {
		_spec.ClearField(dbtarget.FieldDefaultsFile, field.TypeString)
	}
	if value, ok := _u.mutation.Socket(); ok {
		_spec.SetField(dbtarget.FieldSocket, field.TypeString, value)
	}
	if _u.mutation.SocketCleared() {
		_spec.ClearField(dbtarget.FieldSocket, field.TypeString)
	}
	if value, ok := _u.mutation.HeartbeatEnabled(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HeartbeatQuery(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatQuery, field.TypeString, value)
	}
	if _u.mutation.HeartbeatQueryCleared() {
		_spec.ClearField(dbtarget.FieldHeartbeatQuery, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dbtarget.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(dbtarget.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(dbtarget.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LagSeconds(); ok {
		_spec.SetField(dbtarget.FieldLagSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLagSeconds(); ok {
		_spec.AddField(dbtarget.FieldLagSeconds, field.TypeInt64, value)
	}
	if _u.mutation.LagSecondsCleared() {
		_spec.ClearField(dbtarget.FieldLagSeconds, field.TypeInt64)
	}
	if value, ok := _u.mutation.HeartbeatLagSeconds(); ok {
		_spec.SetField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeartbeatLagSeconds(); ok {
		_spec.AddField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64, value)
	}
	if _u.mutation.HeartbeatLagSecondsCleared() {
		_spec.ClearField(dbtarget.FieldHeartbeatLagSeconds, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IoRunning(); ok {
		_spec.SetField(dbtarget.FieldIoRunning, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SQLRunning(); ok {
		_spec.SetField(dbtarget.FieldSQLRunning, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(dbtarget.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(dbtarget.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dbtarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dbtarget.ServerTable,
			Columns: []string{dbtarget.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dbtarget.ServerTable,
			Columns: []string{dbtarget.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DBTarget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dbtarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
