// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"frappe-monitor/ent/logcursor"
	"frappe-monitor/ent/server"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LogCursor is the model entity for the LogCursor schema.
type LogCursor struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// LogPath holds the value of the "log_path" field.
	LogPath string `json:"log_path,omitempty"`
	// ByteOffset holds the value of the "byte_offset" field.
	ByteOffset int64 `json:"byte_offset,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LogCursorQuery when eager-loading is set.
	Edges              LogCursorEdges `json:"edges"`
	server_log_cursors *int
	selectValues       sql.SelectValues
}

// LogCursorEdges holds the relations/edges for other nodes in the graph.
type LogCursorEdges struct {
	// Server holds the value of the server edge.
	Server *Server `json:"server,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServerOrErr returns the Server value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LogCursorEdges) ServerOrErr() (*Server, error) {
	if e.Server != nil {
		return e.Server, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: server.Label}
	}
	return nil, &NotLoadedError{edge: "server"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LogCursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case logcursor.FieldID, logcursor.FieldByteOffset:
			values[i] = new(sql.NullInt64)
		case logcursor.FieldLogPath:
			values[i] = new(sql.NullString)
		case logcursor.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		case logcursor.ForeignKeys[0]: // server_log_cursors
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LogCursor fields.
func (_m *LogCursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case logcursor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case logcursor.FieldLogPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_path", values[i])
			} else if value.Valid {
				_m.LogPath = value.String
			}
		case logcursor.FieldByteOffset:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_offset", values[i])
			} else if value.Valid {
				_m.ByteOffset = value.Int64
			}
		case logcursor.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case logcursor.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field server_log_cursors", value)
			} else if value.Valid {
				_m.server_log_cursors = new(int)
				*_m.server_log_cursors = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LogCursor.
// This includes values selected through modifiers, order, etc.
func (_m *LogCursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryServer queries the "server" edge of the LogCursor entity.
func (_m *LogCursor) QueryServer() *ServerQuery {
	return NewLogCursorClient(_m.config).QueryServer(_m)
}

// Update returns a builder for updating this LogCursor.
// Note that you need to call LogCursor.Unwrap() before calling this method if this LogCursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LogCursor) Update() *LogCursorUpdateOne {
	return NewLogCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LogCursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LogCursor) Unwrap() *LogCursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LogCursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LogCursor) String() string {
	var builder strings.Builder
	builder.WriteString("LogCursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("log_path=")
	builder.WriteString(_m.LogPath)
	builder.WriteString(", ")
	builder.WriteString("byte_offset=")
	builder.WriteString(fmt.Sprintf("%v", _m.ByteOffset))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LogCursors is a parsable slice of LogCursor.
type LogCursors []*LogCursor
