// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/logcursor"
	"frappe-monitor/ent/predicate"
	"frappe-monitor/ent/server"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogCursorUpdate is the builder for updating LogCursor entities.
type LogCursorUpdate struct {
	config
	hooks    []Hook
	mutation *LogCursorMutation
}

// Where appends a list predicates to the LogCursorUpdate builder.
func (_u *LogCursorUpdate) Where(ps ...predicate.LogCursor) *LogCursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLogPath sets the "log_path" field.
func (_u *LogCursorUpdate) SetLogPath(v string) *LogCursorUpdate {
	_u.mutation.SetLogPath(v)
	return _u
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_u *LogCursorUpdate) SetNillableLogPath(v *string) *LogCursorUpdate {
	if v != nil {
		_u.SetLogPath(*v)
	}
	return _u
}

// SetByteOffset sets the "byte_offset" field.
func (_u *LogCursorUpdate) SetByteOffset(v int64) *LogCursorUpdate {
	_u.mutation.ResetByteOffset()
	_u.mutation.SetByteOffset(v)
	return _u
}

// SetNillableByteOffset sets the "byte_offset" field if the given value is not nil.
func (_u *LogCursorUpdate) SetNillableByteOffset(v *int64) *LogCursorUpdate {
	if v != nil {
		_u.SetByteOffset(*v)
	}
	return _u
}

// AddByteOffset adds value to the "byte_offset" field.
func (_u *LogCursorUpdate) AddByteOffset(v int64) *LogCursorUpdate {
	_u.mutation.AddByteOffset(v)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *LogCursorUpdate) SetLastSeenAt(v time.Time) *LogCursorUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *LogCursorUpdate) SetServerID(id int) *LogCursorUpdate {
	_u.mutation.SetServerID(id)
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *LogCursorUpdate) SetServer(v *Server) *LogCursorUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the LogCursorMutation object of the builder.
func (_u *LogCursorUpdate) Mutation() *LogCursorMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *LogCursorUpdate) ClearServer() *LogCursorUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LogCursorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogCursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LogCursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogCursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LogCursorUpdate) defaults() {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := logcursor.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LogCursorUpdate) check() error {
	if v, ok := _u.mutation.LogPath(); ok {
		if err := logcursor.LogPathValidator(v); err != nil {
			return &ValidationError{Name: "log_path", err: fmt.Errorf(`ent: validator failed for field "LogCursor.log_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteOffset(); ok {
		if err := logcursor.ByteOffsetValidator(v); err != nil {
			return &ValidationError{Name: "byte_offset", err: fmt.Errorf(`ent: validator failed for field "LogCursor.byte_offset": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LogCursor.server"`)
	}
	return nil
}

func (_u *LogCursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(logcursor.Table, logcursor.Columns, sqlgraph.NewFieldSpec(logcursor.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LogPath(); ok {
		_spec.SetField(logcursor.FieldLogPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteOffset(); ok {
		_spec.SetField(logcursor.FieldByteOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteOffset(); ok {
		_spec.AddField(logcursor.FieldByteOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(logcursor.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logcursor.ServerTable,
			Columns: []string{logcursor.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logcursor.ServerTable,
			Columns: []string{logcursor.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LogCursorUpdateOne is the builder for updating a single LogCursor entity.
type LogCursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LogCursorMutation
}

// SetLogPath sets the "log_path" field.
func (_u *LogCursorUpdateOne) SetLogPath(v string) *LogCursorUpdateOne {
	_u.mutation.SetLogPath(v)
	return _u
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_u *LogCursorUpdateOne) SetNillableLogPath(v *string) *LogCursorUpdateOne {
	if v != nil {
		_u.SetLogPath(*v)
	}
	return _u
}

// SetByteOffset sets the "byte_offset" field.
func (_u *LogCursorUpdateOne) SetByteOffset(v int64) *LogCursorUpdateOne {
	_u.mutation.ResetByteOffset()
	_u.mutation.SetByteOffset(v)
	return _u
}

// SetNillableByteOffset sets the "byte_offset" field if the given value is not nil.
func (_u *LogCursorUpdateOne) SetNillableByteOffset(v *int64) *LogCursorUpdateOne {
	if v != nil {
		_u.SetByteOffset(*v)
	}
	return _u
}

// AddByteOffset adds value to the "byte_offset" field.
func (_u *LogCursorUpdateOne) AddByteOffset(v int64) *LogCursorUpdateOne {
	_u.mutation.AddByteOffset(v)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *LogCursorUpdateOne) SetLastSeenAt(v time.Time) *LogCursorUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *LogCursorUpdateOne) SetServerID(id int) *LogCursorUpdateOne {
	_u.mutation.SetServerID(id)
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *LogCursorUpdateOne) SetServer(v *Server) *LogCursorUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the LogCursorMutation object of the builder.
func (_u *LogCursorUpdateOne) Mutation() *LogCursorMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *LogCursorUpdateOne) ClearServer() *LogCursorUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the LogCursorUpdate builder.
func (_u *LogCursorUpdateOne) Where(ps ...predicate.LogCursor) *LogCursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LogCursorUpdateOne) Select(field string, fields ...string) *LogCursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LogCursor entity.
func (_u *LogCursorUpdateOne) Save(ctx context.Context) (*LogCursor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogCursorUpdateOne) SaveX(ctx context.Context) *LogCursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LogCursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogCursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LogCursorUpdateOne) defaults() {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := logcursor.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LogCursorUpdateOne) check() error {
	if v, ok := _u.mutation.LogPath(); ok {
		if err := logcursor.LogPathValidator(v); err != nil {
			return &ValidationError{Name: "log_path", err: fmt.Errorf(`ent: validator failed for field "LogCursor.log_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteOffset(); ok {
		if err := logcursor.ByteOffsetValidator(v); err != nil {
			return &ValidationError{Name: "byte_offset", err: fmt.Errorf(`ent: validator failed for field "LogCursor.byte_offset": %w`, err)}
		}
	}
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LogCursor.server"`)
	}
	return nil
}

func (_u *LogCursorUpdateOne) sqlSave(ctx context.Context) (_node *LogCursor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(logcursor.Table, logcursor.Columns, sqlgraph.NewFieldSpec(logcursor.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LogCursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logcursor.FieldID)
		for _, f := range fields {
			if !logcursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logcursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LogPath(); ok {
		_spec.SetField(logcursor.FieldLogPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteOffset(); ok {
		_spec.SetField(logcursor.FieldByteOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteOffset(); ok {
		_spec.AddField(logcursor.FieldByteOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(logcursor.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logcursor.ServerTable,
			Columns: []string{logcursor.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logcursor.ServerTable,
			Columns: []string{logcursor.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LogCursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
