// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/alertstate"
	"frappe-monitor/ent/logcursor"
	"frappe-monitor/ent/predicate"
	"frappe-monitor/ent/server"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAlertState = "AlertState"
	TypeLogCursor  = "LogCursor"
	TypeServer     = "Server"
)

// AlertStateMutation represents an operation that mutates the AlertState nodes in the graph.
type AlertStateMutation struct {
	config
	op               Op
	typ              string
	id               *int
	rule_name        *string
	fingerprint      *string
	labels           *map[string]string
	status           *alertstate.Status
	value            *float64
	addvalue         *float64
	first_fired_at   *time.Time
	last_notified_at *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*AlertState, error)
	predicates       []predicate.AlertState
}

var _ ent.Mutation = (*AlertStateMutation)(nil)

// alertstateOption allows management of the mutation configuration using functional options.
type alertstateOption func(*AlertStateMutation)

// newAlertStateMutation creates new mutation for the AlertState entity.
func newAlertStateMutation(c config, op Op, opts ...alertstateOption) *AlertStateMutation {
	m := &AlertStateMutation{
		config:        c,
		op:            op,
		typ:           TypeAlertState,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAlertStateID sets the ID field of the mutation.
func withAlertStateID(id int) alertstateOption {
	return func(m *AlertStateMutation) {
		var (
			err   error
			once  sync.Once
			value *AlertState
		)
		m.oldValue = func(ctx context.Context) (*AlertState, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AlertState.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAlertState sets the old AlertState of the mutation.
func withAlertState(node *AlertState) alertstateOption {
	return func(m *AlertStateMutation) {
		m.oldValue = func(context.Context) (*AlertState, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AlertStateMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AlertStateMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AlertStateMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AlertStateMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AlertState.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRuleName sets the "rule_name" field.
func (m *AlertStateMutation) SetRuleName(s string) {
	m.rule_name = &s
}

// RuleName returns the value of the "rule_name" field in the mutation.
func (m *AlertStateMutation) RuleName() (r string, exists bool) {
	v := m.rule_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRuleName returns the old "rule_name" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldRuleName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRuleName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRuleName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRuleName: %w", err)
	}
	return oldValue.RuleName, nil
}

// ResetRuleName resets all changes to the "rule_name" field.
func (m *AlertStateMutation) ResetRuleName() {
	m.rule_name = nil
}

// SetFingerprint sets the "fingerprint" field.
func (m *AlertStateMutation) SetFingerprint(s string) {
	m.fingerprint = &s
}

// Fingerprint returns the value of the "fingerprint" field in the mutation.
func (m *AlertStateMutation) Fingerprint() (r string, exists bool) {
	v := m.fingerprint
	if v == nil {
		return
	}
	return *v, true
}

// OldFingerprint returns the old "fingerprint" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldFingerprint(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFingerprint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFingerprint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFingerprint: %w", err)
	}
	return oldValue.Fingerprint, nil
}

// ResetFingerprint resets all changes to the "fingerprint" field.
func (m *AlertStateMutation) ResetFingerprint() {
	m.fingerprint = nil
}

// SetLabels sets the "labels" field.
func (m *AlertStateMutation) SetLabels(value map[string]string) {
	m.labels = &value
}

// Labels returns the value of the "labels" field in the mutation.
func (m *AlertStateMutation) Labels() (r map[string]string, exists bool) {
	v := m.labels
	if v == nil {
		return
	}
	return *v, true
}

// OldLabels returns the old "labels" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldLabels(ctx context.Context) (v map[string]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLabels is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLabels requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLabels: %w", err)
	}
	return oldValue.Labels, nil
}

// ClearLabels clears the value of the "labels" field.
func (m *AlertStateMutation) ClearLabels() {
	m.labels = nil
	m.clearedFields[alertstate.FieldLabels] = struct{}{}
}

// LabelsCleared returns if the "labels" field was cleared in this mutation.
func (m *AlertStateMutation) LabelsCleared() bool {
	_, ok := m.clearedFields[alertstate.FieldLabels]
	return ok
}

// ResetLabels resets all changes to the "labels" field.
func (m *AlertStateMutation) ResetLabels() {
	m.labels = nil
	delete(m.clearedFields, alertstate.FieldLabels)
}

// SetStatus sets the "status" field.
func (m *AlertStateMutation) SetStatus(a alertstate.Status) {
	m.status = &a
}

// Status returns the value of the "status" field in the mutation.
func (m *AlertStateMutation) Status() (r alertstate.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldStatus(ctx context.Context) (v alertstate.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *AlertStateMutation) ResetStatus() {
	m.status = nil
}

// SetValue sets the "value" field.
func (m *AlertStateMutation) SetValue(f float64) {
	m.value = &f
	m.addvalue = nil
}

// Value returns the value of the "value" field in the mutation.
func (m *AlertStateMutation) Value() (r float64, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// AddValue adds f to the "value" field.
func (m *AlertStateMutation) AddValue(f float64) {
	if m.addvalue != nil {
		*m.addvalue += f
	} else {
		m.addvalue = &f
	}
}

// AddedValue returns the value that was added to the "value" field in this mutation.
func (m *AlertStateMutation) AddedValue() (r float64, exists bool) {
	v := m.addvalue
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *AlertStateMutation) ResetValue() {
	m.value = nil
	m.addvalue = nil
}

// SetFirstFiredAt sets the "first_fired_at" field.
func (m *AlertStateMutation) SetFirstFiredAt(t time.Time) {
	m.first_fired_at = &t
}

// FirstFiredAt returns the value of the "first_fired_at" field in the mutation.
func (m *AlertStateMutation) FirstFiredAt() (r time.Time, exists bool) {
	v := m.first_fired_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFirstFiredAt returns the old "first_fired_at" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldFirstFiredAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFirstFiredAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFirstFiredAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFirstFiredAt: %w", err)
	}
	return oldValue.FirstFiredAt, nil
}

// ResetFirstFiredAt resets all changes to the "first_fired_at" field.
func (m *AlertStateMutation) ResetFirstFiredAt() {
	m.first_fired_at = nil
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (m *AlertStateMutation) SetLastNotifiedAt(t time.Time) {
	m.last_notified_at = &t
}

// LastNotifiedAt returns the value of the "last_notified_at" field in the mutation.
func (m *AlertStateMutation) LastNotifiedAt() (r time.Time, exists bool) {
	v := m.last_notified_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastNotifiedAt returns the old "last_notified_at" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldLastNotifiedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastNotifiedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastNotifiedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastNotifiedAt: %w", err)
	}
	return oldValue.LastNotifiedAt, nil
}

// ResetLastNotifiedAt resets all changes to the "last_notified_at" field.
func (m *AlertStateMutation) ResetLastNotifiedAt() {
	m.last_notified_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AlertStateMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AlertStateMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AlertState entity.
// If the AlertState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AlertStateMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AlertStateMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the AlertStateMutation builder.
func (m *AlertStateMutation) Where(ps ...predicate.AlertState) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AlertStateMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AlertStateMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AlertState, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AlertStateMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AlertStateMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AlertState).
func (m *AlertStateMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AlertStateMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.rule_name != nil {
		fields = append(fields, alertstate.FieldRuleName)
	}
	if m.fingerprint != nil {
		fields = append(fields, alertstate.FieldFingerprint)
	}
	if m.labels != nil {
		fields = append(fields, alertstate.FieldLabels)
	}
	if m.status != nil {
		fields = append(fields, alertstate.FieldStatus)
	}
	if m.value != nil {
		fields = append(fields, alertstate.FieldValue)
	}
	if m.first_fired_at != nil {
		fields = append(fields, alertstate.FieldFirstFiredAt)
	}
	if m.last_notified_at != nil {
		fields = append(fields, alertstate.FieldLastNotifiedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, alertstate.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AlertStateMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case alertstate.FieldRuleName:
		return m.RuleName()
	case alertstate.FieldFingerprint:
		return m.Fingerprint()
	case alertstate.FieldLabels:
		return m.Labels()
	case alertstate.FieldStatus:
		return m.Status()
	case alertstate.FieldValue:
		return m.Value()
	case alertstate.FieldFirstFiredAt:
		return m.FirstFiredAt()
	case alertstate.FieldLastNotifiedAt:
		return m.LastNotifiedAt()
	case alertstate.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AlertStateMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case alertstate.FieldRuleName:
		return m.OldRuleName(ctx)
	case alertstate.FieldFingerprint:
		return m.OldFingerprint(ctx)
	case alertstate.FieldLabels:
		return m.OldLabels(ctx)
	case alertstate.FieldStatus:
		return m.OldStatus(ctx)
	case alertstate.FieldValue:
		return m.OldValue(ctx)
	case alertstate.FieldFirstFiredAt:
		return m.OldFirstFiredAt(ctx)
	case alertstate.FieldLastNotifiedAt:
		return m.OldLastNotifiedAt(ctx)
	case alertstate.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AlertState field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AlertStateMutation) SetField(name string, value ent.Value) error {
	switch name {
	case alertstate.FieldRuleName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRuleName(v)
		return nil
	case alertstate.FieldFingerprint:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFingerprint(v)
		return nil
	case alertstate.FieldLabels:
		v, ok := value.(map[string]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLabels(v)
		return nil
	case alertstate.FieldStatus:
		v, ok := value.(alertstate.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case alertstate.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	case alertstate.FieldFirstFiredAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFirstFiredAt(v)
		return nil
	case alertstate.FieldLastNotifiedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastNotifiedAt(v)
		return nil
	case alertstate.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AlertState field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AlertStateMutation) AddedFields() []string {
	var fields []string
	if m.addvalue != nil {
		fields = append(fields, alertstate.FieldValue)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AlertStateMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case alertstate.FieldValue:
		return m.AddedValue()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AlertStateMutation) AddField(name string, value ent.Value) error {
	switch name {
	case alertstate.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue(v)
		return nil
	}
	return fmt.Errorf("unknown AlertState numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AlertStateMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(alertstate.FieldLabels) {
		fields = append(fields, alertstate.FieldLabels)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AlertStateMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AlertStateMutation) ClearField(name string) error {
	switch name {
	case alertstate.FieldLabels:
		m.ClearLabels()
		return nil
	}
	return fmt.Errorf("unknown AlertState nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AlertStateMutation) ResetField(name string) error {
	switch name {
	case alertstate.FieldRuleName:
		m.ResetRuleName()
		return nil
	case alertstate.FieldFingerprint:
		m.ResetFingerprint()
		return nil
	case alertstate.FieldLabels:
		m.ResetLabels()
		return nil
	case alertstate.FieldStatus:
		m.ResetStatus()
		return nil
	case alertstate.FieldValue:
		m.ResetValue()
		return nil
	case alertstate.FieldFirstFiredAt:
		m.ResetFirstFiredAt()
		return nil
	case alertstate.FieldLastNotifiedAt:
		m.ResetLastNotifiedAt()
		return nil
	case alertstate.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown AlertState field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AlertStateMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AlertStateMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AlertStateMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AlertStateMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AlertStateMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AlertStateMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AlertStateMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AlertState unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AlertStateMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AlertState edge %s", name)
}

// LogCursorMutation represents an operation that mutates the LogCursor nodes in the graph.
type LogCursorMutation struct {
	config
	op             Op
	typ            string
	id             *int
	log_path       *string
	byte_offset    *int64
	addbyte_offset *int64
	last_seen_at   *time.Time
	clearedFields  map[string]struct{}
	server         *int
	clearedserver  bool
	done           bool
	oldValue       func(context.Context) (*LogCursor, error)
	predicates     []predicate.LogCursor
}

var _ ent.Mutation = (*LogCursorMutation)(nil)

// logcursorOption allows management of the mutation configuration using functional options.
type logcursorOption func(*LogCursorMutation)

// newLogCursorMutation creates new mutation for the LogCursor entity.
func newLogCursorMutation(c config, op Op, opts ...logcursorOption) *LogCursorMutation {
	m := &LogCursorMutation{
		config:        c,
		op:            op,
		typ:           TypeLogCursor,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLogCursorID sets the ID field of the mutation.
func withLogCursorID(id int) logcursorOption {
	return func(m *LogCursorMutation) {
		var (
			err   error
			once  sync.Once
			value *LogCursor
		)
		m.oldValue = func(ctx context.Context) (*LogCursor, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().LogCursor.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLogCursor sets the old LogCursor of the mutation.
func withLogCursor(node *LogCursor) logcursorOption {
	return func(m *LogCursorMutation) {
		m.oldValue = func(context.Context) (*LogCursor, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LogCursorMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LogCursorMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LogCursorMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LogCursorMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().LogCursor.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetLogPath sets the "log_path" field.
func (m *LogCursorMutation) SetLogPath(s string) {
	m.log_path = &s
}

// LogPath returns the value of the "log_path" field in the mutation.
func (m *LogCursorMutation) LogPath() (r string, exists bool) {
	v := m.log_path
	if v == nil {
		return
	}
	return *v, true
}

// OldLogPath returns the old "log_path" field's value of the LogCursor entity.
// If the LogCursor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LogCursorMutation) OldLogPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogPath: %w", err)
	}
	return oldValue.LogPath, nil
}

// ResetLogPath resets all changes to the "log_path" field.
func (m *LogCursorMutation) ResetLogPath() {
	m.log_path = nil
}

// SetByteOffset sets the "byte_offset" field.
func (m *LogCursorMutation) SetByteOffset(i int64) {
	m.byte_offset = &i
	m.addbyte_offset = nil
}

// ByteOffset returns the value of the "byte_offset" field in the mutation.
func (m *LogCursorMutation) ByteOffset() (r int64, exists bool) {
	v := m.byte_offset
	if v == nil {
		return
	}
	return *v, true
}

// OldByteOffset returns the old "byte_offset" field's value of the LogCursor entity.
// If the LogCursor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LogCursorMutation) OldByteOffset(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldByteOffset is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldByteOffset requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldByteOffset: %w", err)
	}
	return oldValue.ByteOffset, nil
}

// AddByteOffset adds i to the "byte_offset" field.
func (m *LogCursorMutation) AddByteOffset(i int64) {
	if m.addbyte_offset != nil {
		*m.addbyte_offset += i
	} else {
		m.addbyte_offset = &i
	}
}

// AddedByteOffset returns the value that was added to the "byte_offset" field in this mutation.
func (m *LogCursorMutation) AddedByteOffset() (r int64, exists bool) {
	v := m.addbyte_offset
	if v == nil {
		return
	}
	return *v, true
}

// ResetByteOffset resets all changes to the "byte_offset" field.
func (m *LogCursorMutation) ResetByteOffset() {
	m.byte_offset = nil
	m.addbyte_offset = nil
}

// SetLastSeenAt sets the "last_seen_at" field.
func (m *LogCursorMutation) SetLastSeenAt(t time.Time) {
	m.last_seen_at = &t
}

// LastSeenAt returns the value of the "last_seen_at" field in the mutation.
func (m *LogCursorMutation) LastSeenAt() (r time.Time, exists bool) {
	v := m.last_seen_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastSeenAt returns the old "last_seen_at" field's value of the LogCursor entity.
// If the LogCursor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LogCursorMutation) OldLastSeenAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastSeenAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastSeenAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastSeenAt: %w", err)
	}
	return oldValue.LastSeenAt, nil
}

// ResetLastSeenAt resets all changes to the "last_seen_at" field.
func (m *LogCursorMutation) ResetLastSeenAt() {
	m.last_seen_at = nil
}

// SetServerID sets the "server" edge to the Server entity by id.
func (m *LogCursorMutation) SetServerID(id int) {
	m.server = &id
}

// ClearServer clears the "server" edge to the Server entity.
func (m *LogCursorMutation) ClearServer() {
	m.clearedserver = true
}

// ServerCleared reports if the "server" edge to the Server entity was cleared.
func (m *LogCursorMutation) ServerCleared() bool {
	return m.clearedserver
}

// ServerID returns the "server" edge ID in the mutation.
func (m *LogCursorMutation) ServerID() (id int, exists bool) {
	if m.server != nil {
		return *m.server, true
	}
	return
}

// ServerIDs returns the "server" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ServerID instead. It exists only for internal usage by the builders.
func (m *LogCursorMutation) ServerIDs() (ids []int) {
	if id := m.server; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetServer resets all changes to the "server" edge.
func (m *LogCursorMutation) ResetServer() {
	m.server = nil
	m.clearedserver = false
}

// Where appends a list predicates to the LogCursorMutation builder.
func (m *LogCursorMutation) Where(ps ...predicate.LogCursor) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LogCursorMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LogCursorMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.LogCursor, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LogCursorMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LogCursorMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (LogCursor).
func (m *LogCursorMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LogCursorMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.log_path != nil {
		fields = append(fields, logcursor.FieldLogPath)
	}
	if m.byte_offset != nil {
		fields = append(fields, logcursor.FieldByteOffset)
	}
	if m.last_seen_at != nil {
		fields = append(fields, logcursor.FieldLastSeenAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LogCursorMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case logcursor.FieldLogPath:
		return m.LogPath()
	case logcursor.FieldByteOffset:
		return m.ByteOffset()
	case logcursor.FieldLastSeenAt:
		return m.LastSeenAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LogCursorMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case logcursor.FieldLogPath:
		return m.OldLogPath(ctx)
	case logcursor.FieldByteOffset:
		return m.OldByteOffset(ctx)
	case logcursor.FieldLastSeenAt:
		return m.OldLastSeenAt(ctx)
	}
	return nil, fmt.Errorf("unknown LogCursor field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LogCursorMutation) SetField(name string, value ent.Value) error {
	switch name {
	case logcursor.FieldLogPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogPath(v)
		return nil
	case logcursor.FieldByteOffset:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetByteOffset(v)
		return nil
	case logcursor.FieldLastSeenAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastSeenAt(v)
		return nil
	}
	return fmt.Errorf("unknown LogCursor field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LogCursorMutation) AddedFields() []string {
	var fields []string
	if m.addbyte_offset != nil {
		fields = append(fields, logcursor.FieldByteOffset)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LogCursorMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case logcursor.FieldByteOffset:
		return m.AddedByteOffset()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LogCursorMutation) AddField(name string, value ent.Value) error {
	switch name {
	case logcursor.FieldByteOffset:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddByteOffset(v)
		return nil
	}
	return fmt.Errorf("unknown LogCursor numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LogCursorMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LogCursorMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LogCursorMutation) ClearField(name string) error {
	return fmt.Errorf("unknown LogCursor nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LogCursorMutation) ResetField(name string) error {
	switch name {
	case logcursor.FieldLogPath:
		m.ResetLogPath()
		return nil
	case logcursor.FieldByteOffset:
		m.ResetByteOffset()
		return nil
	case logcursor.FieldLastSeenAt:
		m.ResetLastSeenAt()
		return nil
	}
	return fmt.Errorf("unknown LogCursor field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LogCursorMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.server != nil {
		edges = append(edges, logcursor.EdgeServer)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LogCursorMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case logcursor.EdgeServer:
		if id := m.server; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LogCursorMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LogCursorMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LogCursorMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedserver {
		edges = append(edges, logcursor.EdgeServer)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LogCursorMutation) EdgeCleared(name string) bool {
	switch name {
	case logcursor.EdgeServer:
		return m.clearedserver
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LogCursorMutation) ClearEdge(name string) error {
	switch name {
	case logcursor.EdgeServer:
		m.ClearServer()
		return nil
	}
	return fmt.Errorf("unknown LogCursor unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LogCursorMutation) ResetEdge(name string) error {
	switch name {
	case logcursor.EdgeServer:
		m.ResetServer()
		return nil
	}
	return fmt.Errorf("unknown LogCursor edge %s", name)
}

// ServerMutation represents an operation that mutates the Server nodes in the graph.
type ServerMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	name               *string
	hostname           *string
	ssh_user           *string
	ssh_port           *int
	addssh_port        *int
	ssh_key_path       *string
	bench_paths        *[]string
	appendbench_paths  []string
	labels             *map[string]string
	status             *server.Status
	last_pinged_at     *time.Time
	last_error         *string
	created_at         *time.Time
	updated_at         *time.Time
	clearedFields      map[string]struct{}
	log_cursors        map[int]struct{}
	removedlog_cursors map[int]struct{}
	clearedlog_cursors bool
	done               bool
	oldValue           func(context.Context) (*Server, error)
	predicates         []predicate.Server
}

var _ ent.Mutation = (*ServerMutation)(nil)

// serverOption allows management of the mutation configuration using functional options.
type serverOption func(*ServerMutation)

// newServerMutation creates new mutation for the Server entity.
func newServerMutation(c config, op Op, opts ...serverOption) *ServerMutation {
	m := &ServerMutation{
		config:        c,
		op:            op,
		typ:           TypeServer,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withServerID sets the ID field of the mutation.
func withServerID(id int) serverOption {
	return func(m *ServerMutation) {
		var (
			err   error
			once  sync.Once
			value *Server
		)
		m.oldValue = func(ctx context.Context) (*Server, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Server.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withServer sets the old Server of the mutation.
func withServer(node *Server) serverOption {
	return func(m *ServerMutation) {
		m.oldValue = func(context.Context) (*Server, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ServerMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ServerMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ServerMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ServerMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Server.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ServerMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ServerMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ServerMutation) ResetName() {
	m.name = nil
}

// SetHostname sets the "hostname" field.
func (m *ServerMutation) SetHostname(s string) {
	m.hostname = &s
}

// Hostname returns the value of the "hostname" field in the mutation.
func (m *ServerMutation) Hostname() (r string, exists bool) {
	v := m.hostname
	if v == nil {
		return
	}
	return *v, true
}

// OldHostname returns the old "hostname" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldHostname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHostname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHostname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHostname: %w", err)
	}
	return oldValue.Hostname, nil
}

// ResetHostname resets all changes to the "hostname" field.
func (m *ServerMutation) ResetHostname() {
	m.hostname = nil
}

// SetSSHUser sets the "ssh_user" field.
func (m *ServerMutation) SetSSHUser(s string) {
	m.ssh_user = &s
}

// SSHUser returns the value of the "ssh_user" field in the mutation.
func (m *ServerMutation) SSHUser() (r string, exists bool) {
	v := m.ssh_user
	if v == nil {
		return
	}
	return *v, true
}

// OldSSHUser returns the old "ssh_user" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldSSHUser(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSSHUser is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSSHUser requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSSHUser: %w", err)
	}
	return oldValue.SSHUser, nil
}

// ResetSSHUser resets all changes to the "ssh_user" field.
func (m *ServerMutation) ResetSSHUser() {
	m.ssh_user = nil
}

// SetSSHPort sets the "ssh_port" field.
func (m *ServerMutation) SetSSHPort(i int) {
	m.ssh_port = &i
	m.addssh_port = nil
}

// SSHPort returns the value of the "ssh_port" field in the mutation.
func (m *ServerMutation) SSHPort() (r int, exists bool) {
	v := m.ssh_port
	if v == nil {
		return
	}
	return *v, true
}

// OldSSHPort returns the old "ssh_port" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldSSHPort(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSSHPort is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSSHPort requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSSHPort: %w", err)
	}
	return oldValue.SSHPort, nil
}

// AddSSHPort adds i to the "ssh_port" field.
func (m *ServerMutation) AddSSHPort(i int) {
	if m.addssh_port != nil {
		*m.addssh_port += i
	} else {
		m.addssh_port = &i
	}
}

// AddedSSHPort returns the value that was added to the "ssh_port" field in this mutation.
func (m *ServerMutation) AddedSSHPort() (r int, exists bool) {
	v := m.addssh_port
	if v == nil {
		return
	}
	return *v, true
}

// ResetSSHPort resets all changes to the "ssh_port" field.
func (m *ServerMutation) ResetSSHPort() {
	m.ssh_port = nil
	m.addssh_port = nil
}

// SetSSHKeyPath sets the "ssh_key_path" field.
func (m *ServerMutation) SetSSHKeyPath(s string) {
	m.ssh_key_path = &s
}

// SSHKeyPath returns the value of the "ssh_key_path" field in the mutation.
func (m *ServerMutation) SSHKeyPath() (r string, exists bool) {
	v := m.ssh_key_path
	if v == nil {
		return
	}
	return *v, true
}

// OldSSHKeyPath returns the old "ssh_key_path" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldSSHKeyPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSSHKeyPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSSHKeyPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSSHKeyPath: %w", err)
	}
	return oldValue.SSHKeyPath, nil
}

// ResetSSHKeyPath resets all changes to the "ssh_key_path" field.
func (m *ServerMutation) ResetSSHKeyPath() {
	m.ssh_key_path = nil
}

// SetBenchPaths sets the "bench_paths" field.
func (m *ServerMutation) SetBenchPaths(s []string) {
	m.bench_paths = &s
	m.appendbench_paths = nil
}

// BenchPaths returns the value of the "bench_paths" field in the mutation.
func (m *ServerMutation) BenchPaths() (r []string, exists bool) {
	v := m.bench_paths
	if v == nil {
		return
	}
	return *v, true
}

// OldBenchPaths returns the old "bench_paths" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldBenchPaths(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBenchPaths is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBenchPaths requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBenchPaths: %w", err)
	}
	return oldValue.BenchPaths, nil
}

// AppendBenchPaths adds s to the "bench_paths" field.
func (m *ServerMutation) AppendBenchPaths(s []string) {
	m.appendbench_paths = append(m.appendbench_paths, s...)
}

// AppendedBenchPaths returns the list of values that were appended to the "bench_paths" field in this mutation.
func (m *ServerMutation) AppendedBenchPaths() ([]string, bool) {
	if len(m.appendbench_paths) == 0 {
		return nil, false
	}
	return m.appendbench_paths, true
}

// ClearBenchPaths clears the value of the "bench_paths" field.
func (m *ServerMutation) ClearBenchPaths() {
	m.bench_paths = nil
	m.appendbench_paths = nil
	m.clearedFields[server.FieldBenchPaths] = struct{}{}
}

// BenchPathsCleared returns if the "bench_paths" field was cleared in this mutation.
func (m *ServerMutation) BenchPathsCleared() bool {
	_, ok := m.clearedFields[server.FieldBenchPaths]
	return ok
}

// ResetBenchPaths resets all changes to the "bench_paths" field.
func (m *ServerMutation) ResetBenchPaths() {
	m.bench_paths = nil
	m.appendbench_paths = nil
	delete(m.clearedFields, server.FieldBenchPaths)
}

// SetLabels sets the "labels" field.
func (m *ServerMutation) SetLabels(value map[string]string) {
	m.labels = &value
}

// Labels returns the value of the "labels" field in the mutation.
func (m *ServerMutation) Labels() (r map[string]string, exists bool) {
	v := m.labels
	if v == nil {
		return
	}
	return *v, true
}

// OldLabels returns the old "labels" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldLabels(ctx context.Context) (v map[string]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLabels is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLabels requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLabels: %w", err)
	}
	return oldValue.Labels, nil
}

// ClearLabels clears the value of the "labels" field.
func (m *ServerMutation) ClearLabels() {
	m.labels = nil
	m.clearedFields[server.FieldLabels] = struct{}{}
}

// LabelsCleared returns if the "labels" field was cleared in this mutation.
func (m *ServerMutation) LabelsCleared() bool {
	_, ok := m.clearedFields[server.FieldLabels]
	return ok
}

// ResetLabels resets all changes to the "labels" field.
func (m *ServerMutation) ResetLabels() {
	m.labels = nil
	delete(m.clearedFields, server.FieldLabels)
}

// SetStatus sets the "status" field.
func (m *ServerMutation) SetStatus(s server.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *ServerMutation) Status() (r server.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldStatus(ctx context.Context) (v server.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ServerMutation) ResetStatus() {
	m.status = nil
}

// SetLastPingedAt sets the "last_pinged_at" field.
func (m *ServerMutation) SetLastPingedAt(t time.Time) {
	m.last_pinged_at = &t
}

// LastPingedAt returns the value of the "last_pinged_at" field in the mutation.
func (m *ServerMutation) LastPingedAt() (r time.Time, exists bool) {
	v := m.last_pinged_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastPingedAt returns the old "last_pinged_at" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldLastPingedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastPingedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastPingedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastPingedAt: %w", err)
	}
	return oldValue.LastPingedAt, nil
}

// ClearLastPingedAt clears the value of the "last_pinged_at" field.
func (m *ServerMutation) ClearLastPingedAt() {
	m.last_pinged_at = nil
	m.clearedFields[server.FieldLastPingedAt] = struct{}{}
}

// LastPingedAtCleared returns if the "last_pinged_at" field was cleared in this mutation.
func (m *ServerMutation) LastPingedAtCleared() bool {
	_, ok := m.clearedFields[server.FieldLastPingedAt]
	return ok
}

// ResetLastPingedAt resets all changes to the "last_pinged_at" field.
func (m *ServerMutation) ResetLastPingedAt() {
	m.last_pinged_at = nil
	delete(m.clearedFields, server.FieldLastPingedAt)
}

// SetLastError sets the "last_error" field.
func (m *ServerMutation) SetLastError(s string) {
	m.last_error = &s
}

// LastError returns the value of the "last_error" field in the mutation.
func (m *ServerMutation) LastError() (r string, exists bool) {
	v := m.last_error
	if v == nil {
		return
	}
	return *v, true
}

// OldLastError returns the old "last_error" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldLastError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastError: %w", err)
	}
	return oldValue.LastError, nil
}

// ClearLastError clears the value of the "last_error" field.
func (m *ServerMutation) ClearLastError() {
	m.last_error = nil
	m.clearedFields[server.FieldLastError] = struct{}{}
}

// LastErrorCleared returns if the "last_error" field was cleared in this mutation.
func (m *ServerMutation) LastErrorCleared() bool {
	_, ok := m.clearedFields[server.FieldLastError]
	return ok
}

// ResetLastError resets all changes to the "last_error" field.
func (m *ServerMutation) ResetLastError() {
	m.last_error = nil
	delete(m.clearedFields, server.FieldLastError)
}

// SetCreatedAt sets the "created_at" field.
func (m *ServerMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ServerMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ServerMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ServerMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ServerMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Server entity.
// If the Server object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ServerMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ServerMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddLogCursorIDs adds the "log_cursors" edge to the LogCursor entity by ids.
func (m *ServerMutation) AddLogCursorIDs(ids ...int) {
	if m.log_cursors == nil {
		m.log_cursors = make(map[int]struct{})
	}
	for i := range ids {
		m.log_cursors[ids[i]] = struct{}{}
	}
}

// ClearLogCursors clears the "log_cursors" edge to the LogCursor entity.
func (m *ServerMutation) ClearLogCursors() {
	m.clearedlog_cursors = true
}

// LogCursorsCleared reports if the "log_cursors" edge to the LogCursor entity was cleared.
func (m *ServerMutation) LogCursorsCleared() bool {
	return m.clearedlog_cursors
}

// RemoveLogCursorIDs removes the "log_cursors" edge to the LogCursor entity by IDs.
func (m *ServerMutation) RemoveLogCursorIDs(ids ...int) {
	if m.removedlog_cursors == nil {
		m.removedlog_cursors = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.log_cursors, ids[i])
		m.removedlog_cursors[ids[i]] = struct{}{}
	}
}

// RemovedLogCursors returns the removed IDs of the "log_cursors" edge to the LogCursor entity.
func (m *ServerMutation) RemovedLogCursorsIDs() (ids []int) {
	for id := range m.removedlog_cursors {
		ids = append(ids, id)
	}
	return
}

// LogCursorsIDs returns the "log_cursors" edge IDs in the mutation.
func (m *ServerMutation) LogCursorsIDs() (ids []int) {
	for id := range m.log_cursors {
		ids = append(ids, id)
	}
	return
}

// ResetLogCursors resets all changes to the "log_cursors" edge.
func (m *ServerMutation) ResetLogCursors() {
	m.log_cursors = nil
	m.clearedlog_cursors = false
	m.removedlog_cursors = nil
}

// Where appends a list predicates to the ServerMutation builder.
func (m *ServerMutation) Where(ps ...predicate.Server) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ServerMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ServerMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Server, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ServerMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ServerMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Server).
func (m *ServerMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ServerMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.name != nil {
		fields = append(fields, server.FieldName)
	}
	if m.hostname != nil {
		fields = append(fields, server.FieldHostname)
	}
	if m.ssh_user != nil {
		fields = append(fields, server.FieldSSHUser)
	}
	if m.ssh_port != nil {
		fields = append(fields, server.FieldSSHPort)
	}
	if m.ssh_key_path != nil {
		fields = append(fields, server.FieldSSHKeyPath)
	}
	if m.bench_paths != nil {
		fields = append(fields, server.FieldBenchPaths)
	}
	if m.labels != nil {
		fields = append(fields, server.FieldLabels)
	}
	if m.status != nil {
		fields = append(fields, server.FieldStatus)
	}
	if m.last_pinged_at != nil {
		fields = append(fields, server.FieldLastPingedAt)
	}
	if m.last_error != nil {
		fields = append(fields, server.FieldLastError)
	}
	if m.created_at != nil {
		fields = append(fields, server.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, server.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ServerMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case server.FieldName:
		return m.Name()
	case server.FieldHostname:
		return m.Hostname()
	case server.FieldSSHUser:
		return m.SSHUser()
	case server.FieldSSHPort:
		return m.SSHPort()
	case server.FieldSSHKeyPath:
		return m.SSHKeyPath()
	case server.FieldBenchPaths:
		return m.BenchPaths()
	case server.FieldLabels:
		return m.Labels()
	case server.FieldStatus:
		return m.Status()
	case server.FieldLastPingedAt:
		return m.LastPingedAt()
	case server.FieldLastError:
		return m.LastError()
	case server.FieldCreatedAt:
		return m.CreatedAt()
	case server.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ServerMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case server.FieldName:
		return m.OldName(ctx)
	case server.FieldHostname:
		return m.OldHostname(ctx)
	case server.FieldSSHUser:
		return m.OldSSHUser(ctx)
	case server.FieldSSHPort:
		return m.OldSSHPort(ctx)
	case server.FieldSSHKeyPath:
		return m.OldSSHKeyPath(ctx)
	case server.FieldBenchPaths:
		return m.OldBenchPaths(ctx)
	case server.FieldLabels:
		return m.OldLabels(ctx)
	case server.FieldStatus:
		return m.OldStatus(ctx)
	case server.FieldLastPingedAt:
		return m.OldLastPingedAt(ctx)
	case server.FieldLastError:
		return m.OldLastError(ctx)
	case server.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case server.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Server field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ServerMutation) SetField(name string, value ent.Value) error {
	switch name {
	case server.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case server.FieldHostname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHostname(v)
		return nil
	case server.FieldSSHUser:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSSHUser(v)
		return nil
	case server.FieldSSHPort:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSSHPort(v)
		return nil
	case server.FieldSSHKeyPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSSHKeyPath(v)
		return nil
	case server.FieldBenchPaths:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBenchPaths(v)
		return nil
	case server.FieldLabels:
		v, ok := value.(map[string]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLabels(v)
		return nil
	case server.FieldStatus:
		v, ok := value.(server.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case server.FieldLastPingedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastPingedAt(v)
		return nil
	case server.FieldLastError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastError(v)
		return nil
	case server.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case server.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Server field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ServerMutation) AddedFields() []string {
	var fields []string
	if m.addssh_port != nil {
		fields = append(fields, server.FieldSSHPort)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ServerMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case server.FieldSSHPort:
		return m.AddedSSHPort()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ServerMutation) AddField(name string, value ent.Value) error {
	switch name {
	case server.FieldSSHPort:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSSHPort(v)
		return nil
	}
	return fmt.Errorf("unknown Server numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ServerMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(server.FieldBenchPaths) {
		fields = append(fields, server.FieldBenchPaths)
	}
	if m.FieldCleared(server.FieldLabels) {
		fields = append(fields, server.FieldLabels)
	}
	if m.FieldCleared(server.FieldLastPingedAt) {
		fields = append(fields, server.FieldLastPingedAt)
	}
	if m.FieldCleared(server.FieldLastError) {
		fields = append(fields, server.FieldLastError)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ServerMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ServerMutation) ClearField(name string) error {
	switch name {
	case server.FieldBenchPaths:
		m.ClearBenchPaths()
		return nil
	case server.FieldLabels:
		m.ClearLabels()
		return nil
	case server.FieldLastPingedAt:
		m.ClearLastPingedAt()
		return nil
	case server.FieldLastError:
		m.ClearLastError()
		return nil
	}
	return fmt.Errorf("unknown Server nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ServerMutation) ResetField(name string) error {
	switch name {
	case server.FieldName:
		m.ResetName()
		return nil
	case server.FieldHostname:
		m.ResetHostname()
		return nil
	case server.FieldSSHUser:
		m.ResetSSHUser()
		return nil
	case server.FieldSSHPort:
		m.ResetSSHPort()
		return nil
	case server.FieldSSHKeyPath:
		m.ResetSSHKeyPath()
		return nil
	case server.FieldBenchPaths:
		m.ResetBenchPaths()
		return nil
	case server.FieldLabels:
		m.ResetLabels()
		return nil
	case server.FieldStatus:
		m.ResetStatus()
		return nil
	case server.FieldLastPingedAt:
		m.ResetLastPingedAt()
		return nil
	case server.FieldLastError:
		m.ResetLastError()
		return nil
	case server.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case server.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Server field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ServerMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.log_cursors != nil {
		edges = append(edges, server.EdgeLogCursors)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ServerMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case server.EdgeLogCursors:
		ids := make([]ent.Value, 0, len(m.log_cursors))
		for id := range m.log_cursors {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ServerMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedlog_cursors != nil {
		edges = append(edges, server.EdgeLogCursors)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ServerMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case server.EdgeLogCursors:
		ids := make([]ent.Value, 0, len(m.removedlog_cursors))
		for id := range m.removedlog_cursors {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ServerMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedlog_cursors {
		edges = append(edges, server.EdgeLogCursors)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ServerMutation) EdgeCleared(name string) bool {
	switch name {
	case server.EdgeLogCursors:
		return m.clearedlog_cursors
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ServerMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Server unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ServerMutation) ResetEdge(name string) error {
	switch name {
	case server.EdgeLogCursors:
		m.ResetLogCursors()
		return nil
	}
	return fmt.Errorf("unknown Server edge %s", name)
}
