// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/patchlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PatchLogCreate is the builder for creating a PatchLog entity.
type PatchLogCreate struct {
	config
	mutation *PatchLogMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PatchLogCreate) SetName(v string) *PatchLogCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAppliedAt sets the "applied_at" field.
func (_c *PatchLogCreate) SetAppliedAt(v time.Time) *PatchLogCreate {
	_c.mutation.SetAppliedAt(v)
	return _c
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_c *PatchLogCreate) SetNillableAppliedAt(v *time.Time) *PatchLogCreate {
	if v != nil {
		_c.SetAppliedAt(*v)
	}
	return _c
}

// Mutation returns the PatchLogMutation object of the builder.
func (_c *PatchLogCreate) Mutation() *PatchLogMutation {
	return _c.mutation
}

// Save creates the PatchLog in the database.
func (_c *PatchLogCreate) Save(ctx context.Context) (*PatchLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PatchLogCreate) SaveX(ctx context.Context) *PatchLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatchLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatchLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PatchLogCreate) defaults() {
	if _, ok := _c.mutation.AppliedAt(); !ok {
		v := patchlog.DefaultAppliedAt()
		_c.mutation.SetAppliedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PatchLogCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PatchLog.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := patchlog.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PatchLog.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppliedAt(); !ok {
		return &ValidationError{Name: "applied_at", err: errors.New(`ent: missing required field "PatchLog.applied_at"`)}
	}
	return nil
}

func (_c *PatchLogCreate) sqlSave(ctx context.Context) (*PatchLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PatchLogCreate) createSpec() (*PatchLog, *sqlgraph.CreateSpec) {
	var (
		_node = &PatchLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(patchlog.Table, sqlgraph.NewFieldSpec(patchlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(patchlog.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AppliedAt(); ok {
		_spec.SetField(patchlog.FieldAppliedAt, field.TypeTime, value)
		_node.AppliedAt = value
	}
	return _node, _spec
}

// PatchLogCreateBulk is the builder for creating many PatchLog entities in bulk.
type PatchLogCreateBulk struct {
	config
	err      error
	builders []*PatchLogCreate
}

// Save creates the PatchLog entities in the database.
func (_c *PatchLogCreateBulk) Save(ctx context.Context) ([]*PatchLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PatchLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PatchLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PatchLogCreateBulk) SaveX(ctx context.Context) []*PatchLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatchLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatchLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
