// Code generated by ent, DO NOT EDIT.

package ent

import (
	"frappe-monitor/ent/schema"
	"frappe-monitor/ent/server"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	serverFields := schema.Server{}.Fields()
	_ = serverFields
	// serverDescName is the schema descriptor for name field.
	serverDescName := serverFields[0].Descriptor()
	// server.NameValidator is a validator for the "name" field. It is called by the builders before save.
	server.NameValidator = serverDescName.Validators[0].(func(string) error)
	// serverDescHostname is the schema descriptor for hostname field.
	serverDescHostname := serverFields[1].Descriptor()
	// server.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	server.HostnameValidator = serverDescHostname.Validators[0].(func(string) error)
	// serverDescSSHUser is the schema descriptor for ssh_user field.
	serverDescSSHUser := serverFields[2].Descriptor()
	// server.DefaultSSHUser holds the default value on creation for the ssh_user field.
	server.DefaultSSHUser = serverDescSSHUser.Default.(string)
	// serverDescSSHPort is the schema descriptor for ssh_port field.
	serverDescSSHPort := serverFields[3].Descriptor()
	// server.DefaultSSHPort holds the default value on creation for the ssh_port field.
	server.DefaultSSHPort = serverDescSSHPort.Default.(int)
	// server.SSHPortValidator is a validator for the "ssh_port" field. It is called by the builders before save.
	server.SSHPortValidator = serverDescSSHPort.Validators[0].(func(int) error)
	// serverDescSSHKeyPath is the schema descriptor for ssh_key_path field.
	serverDescSSHKeyPath := serverFields[4].Descriptor()
	// server.SSHKeyPathValidator is a validator for the "ssh_key_path" field. It is called by the builders before save.
	server.SSHKeyPathValidator = serverDescSSHKeyPath.Validators[0].(func(string) error)
	// serverDescCreatedAt is the schema descriptor for created_at field.
	serverDescCreatedAt := serverFields[9].Descriptor()
	// server.DefaultCreatedAt holds the default value on creation for the created_at field.
	server.DefaultCreatedAt = serverDescCreatedAt.Default.(func() time.Time)
	// serverDescUpdatedAt is the schema descriptor for updated_at field.
	serverDescUpdatedAt := serverFields[10].Descriptor()
	// server.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	server.DefaultUpdatedAt = serverDescUpdatedAt.Default.(func() time.Time)
	// server.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	server.UpdateDefaultUpdatedAt = serverDescUpdatedAt.UpdateDefault.(func() time.Time)
}
