// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"frappe-monitor/ent/server"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Server is the model entity for the Server schema.
type Server struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Hostname holds the value of the "hostname" field.
	Hostname string `json:"hostname,omitempty"`
	// SSHUser holds the value of the "ssh_user" field.
	SSHUser string `json:"ssh_user,omitempty"`
	// SSHPort holds the value of the "ssh_port" field.
	SSHPort int `json:"ssh_port,omitempty"`
	// SSHKeyPath holds the value of the "ssh_key_path" field.
	SSHKeyPath string `json:"ssh_key_path,omitempty"`
	// BenchPaths holds the value of the "bench_paths" field.
	BenchPaths []string `json:"bench_paths,omitempty"`
	// Labels holds the value of the "labels" field.
	Labels map[string]string `json:"labels,omitempty"`
	// Status holds the value of the "status" field.
	Status server.Status `json:"status,omitempty"`
	// LastPingedAt holds the value of the "last_pinged_at" field.
	LastPingedAt *time.Time `json:"last_pinged_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServerQuery when eager-loading is set.
	Edges        ServerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServerEdges holds the relations/edges for other nodes in the graph.
type ServerEdges struct {
	// LogCursors holds the value of the log_cursors edge.
	LogCursors []*LogCursor `json:"log_cursors,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LogCursorsOrErr returns the LogCursors value or an error if the edge
// was not loaded in eager-loading.
func (e ServerEdges) LogCursorsOrErr() ([]*LogCursor, error) {
	if e.loadedTypes[0] {
		return e.LogCursors, nil
	}
	return nil, &NotLoadedError{edge: "log_cursors"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Server) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case server.FieldBenchPaths, server.FieldLabels:
			values[i] = new([]byte)
		case server.FieldID, server.FieldSSHPort:
			values[i] = new(sql.NullInt64)
		case server.FieldName, server.FieldHostname, server.FieldSSHUser, server.FieldSSHKeyPath, server.FieldStatus, server.FieldLastError:
			values[i] = new(sql.NullString)
		case server.FieldLastPingedAt, server.FieldCreatedAt, server.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Server fields.
func (_m *Server) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case server.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case server.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case server.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				_m.Hostname = value.String
			}
		case server.FieldSSHUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_user", values[i])
			} else if value.Valid {
				_m.SSHUser = value.String
			}
		case server.FieldSSHPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_port", values[i])
			} else if value.Valid {
				_m.SSHPort = int(value.Int64)
			}
		case server.FieldSSHKeyPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_key_path", values[i])
			} else if value.Valid {
				_m.SSHKeyPath = value.String
			}
		case server.FieldBenchPaths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bench_paths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BenchPaths); err != nil {
					return fmt.Errorf("unmarshal field bench_paths: %w", err)
				}
			}
		case server.FieldLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Labels); err != nil {
					return fmt.Errorf("unmarshal field labels: %w", err)
				}
			}
		case server.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = server.Status(value.String)
			}
		case server.FieldLastPingedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_pinged_at", values[i])
			} else if value.Valid {
				_m.LastPingedAt = new(time.Time)
				*_m.LastPingedAt = value.Time
			}
		case server.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case server.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case server.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Server.
// This includes values selected through modifiers, order, etc.
func (_m *Server) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLogCursors queries the "log_cursors" edge of the Server entity.
func (_m *Server) QueryLogCursors() *LogCursorQuery {
	return NewServerClient(_m.config).QueryLogCursors(_m)
}

// Update returns a builder for updating this Server.
// Note that you need to call Server.Unwrap() before calling this method if this Server
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Server) Update() *ServerUpdateOne {
	return NewServerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Server entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Server) Unwrap() *Server {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Server is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Server) String() string {
	var builder strings.Builder
	builder.WriteString("Server(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("hostname=")
	builder.WriteString(_m.Hostname)
	builder.WriteString(", ")
	builder.WriteString("ssh_user=")
	builder.WriteString(_m.SSHUser)
	builder.WriteString(", ")
	builder.WriteString("ssh_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.SSHPort))
	builder.WriteString(", ")
	builder.WriteString("ssh_key_path=")
	builder.WriteString(_m.SSHKeyPath)
	builder.WriteString(", ")
	builder.WriteString("bench_paths=")
	builder.WriteString(fmt.Sprintf("%v", _m.BenchPaths))
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.LastPingedAt; v != nil {
		builder.WriteString("last_pinged_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Servers is a parsable slice of Server.
type Servers []*Server
