// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"frappe-monitor/ent/predicate"
	"frappe-monitor/ent/server"
	"frappe-monitor/ent/systemsnapshot"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemSnapshotUpdate is the builder for updating SystemSnapshot entities.
type SystemSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SystemSnapshotMutation
}

// Where appends a list predicates to the SystemSnapshotUpdate builder.
func (_u *SystemSnapshotUpdate) Where(ps ...predicate.SystemSnapshot) *SystemSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *SystemSnapshotUpdate) SetCapturedAt(v time.Time) *SystemSnapshotUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SystemSnapshotUpdate) SetPayload(v []byte) *SystemSnapshotUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SystemSnapshotUpdate) SetLastError(v string) *SystemSnapshotUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SystemSnapshotUpdate) SetNillableLastError(v *string) *SystemSnapshotUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *SystemSnapshotUpdate) ClearLastError() *SystemSnapshotUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *SystemSnapshotUpdate) SetServerID(id int) *SystemSnapshotUpdate {
	_u.mutation.SetServerID(id)
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *SystemSnapshotUpdate) SetServer(v *Server) *SystemSnapshotUpdate {
	return _u.SetServerID(v.ID)
}

// Mutation returns the SystemSnapshotMutation object of the builder.
func (_u *SystemSnapshotUpdate) Mutation() *SystemSnapshotMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *SystemSnapshotUpdate) ClearServer() *SystemSnapshotUpdate {
	_u.mutation.ClearServer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemSnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemSnapshotUpdate) defaults() {
	if _, ok := _u.mutation.CapturedAt(); !ok {
		v := systemsnapshot.UpdateDefaultCapturedAt()
		_u.mutation.SetCapturedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemSnapshotUpdate) check() error {
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemSnapshot.server"`)
	}
	return nil
}

func (_u *SystemSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemsnapshot.Table, systemsnapshot.Columns, sqlgraph.NewFieldSpec(systemsnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(systemsnapshot.FieldCapturedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(systemsnapshot.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(systemsnapshot.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(systemsnapshot.FieldLastError, field.TypeString)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   systemsnapshot.ServerTable,
			Columns: []string{systemsnapshot.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   systemsnapshot.ServerTable,
			Columns: []string{systemsnapshot.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemSnapshotUpdateOne is the builder for updating a single SystemSnapshot entity.
type SystemSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemSnapshotMutation
}

// SetCapturedAt sets the "captured_at" field.
func (_u *SystemSnapshotUpdateOne) SetCapturedAt(v time.Time) *SystemSnapshotUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SystemSnapshotUpdateOne) SetPayload(v []byte) *SystemSnapshotUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SystemSnapshotUpdateOne) SetLastError(v string) *SystemSnapshotUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SystemSnapshotUpdateOne) SetNillableLastError(v *string) *SystemSnapshotUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *SystemSnapshotUpdateOne) ClearLastError() *SystemSnapshotUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetServerID sets the "server" edge to the Server entity by ID.
func (_u *SystemSnapshotUpdateOne) SetServerID(id int) *SystemSnapshotUpdateOne {
	_u.mutation.SetServerID(id)
	return _u
}

// SetServer sets the "server" edge to the Server entity.
func (_u *SystemSnapshotUpdateOne) SetServer(v *Server) *SystemSnapshotUpdateOne {
	return _u.SetServerID(v.ID)
}

// Mutation returns the SystemSnapshotMutation object of the builder.
func (_u *SystemSnapshotUpdateOne) Mutation() *SystemSnapshotMutation {
	return _u.mutation
}

// ClearServer clears the "server" edge to the Server entity.
func (_u *SystemSnapshotUpdateOne) ClearServer() *SystemSnapshotUpdateOne {
	_u.mutation.ClearServer()
	return _u
}

// Where appends a list predicates to the SystemSnapshotUpdate builder.
func (_u *SystemSnapshotUpdateOne) Where(ps ...predicate.SystemSnapshot) *SystemSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemSnapshotUpdateOne) Select(field string, fields ...string) *SystemSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemSnapshot entity.
func (_u *SystemSnapshotUpdateOne) Save(ctx context.Context) (*SystemSnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemSnapshotUpdateOne) SaveX(ctx context.Context) *SystemSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemSnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.CapturedAt(); !ok {
		v := systemsnapshot.UpdateDefaultCapturedAt()
		_u.mutation.SetCapturedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemSnapshotUpdateOne) check() error {
	if _u.mutation.ServerCleared() && len(_u.mutation.ServerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SystemSnapshot.server"`)
	}
	return nil
}

func (_u *SystemSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *SystemSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemsnapshot.Table, systemsnapshot.Columns, sqlgraph.NewFieldSpec(systemsnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemsnapshot.FieldID)
		for _, f := range fields {
			if !systemsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(systemsnapshot.FieldCapturedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(systemsnapshot.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(systemsnapshot.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(systemsnapshot.FieldLastError, field.TypeString)
	}
	if _u.mutation.ServerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   systemsnapshot.ServerTable,
			Columns: []string{systemsnapshot.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   systemsnapshot.ServerTable,
			Columns: []string{systemsnapshot.ServerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(server.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SystemSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
