// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"frappe-monitor/ent/predicate"
	"frappe-monitor/ent/systemsnapshot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemSnapshotDelete is the builder for deleting a SystemSnapshot entity.
type SystemSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *SystemSnapshotMutation
}

// Where appends a list predicates to the SystemSnapshotDelete builder.
func (_d *SystemSnapshotDelete) Where(ps ...predicate.SystemSnapshot) *SystemSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SystemSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SystemSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SystemSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(systemsnapshot.Table, sqlgraph.NewFieldSpec(systemsnapshot.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SystemSnapshotDeleteOne is the builder for deleting a single SystemSnapshot entity.
type SystemSnapshotDeleteOne struct {
	_d *SystemSnapshotDelete
}

// Where appends a list predicates to the SystemSnapshotDelete builder.
func (_d *SystemSnapshotDeleteOne) Where(ps ...predicate.SystemSnapshot) *SystemSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SystemSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{systemsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SystemSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
