// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AlertState is the predicate function for alertstate builders.
type AlertState func(*sql.Selector)

// LogCursor is the predicate function for logcursor builders.
type LogCursor func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)
